/* OasisDeal editorial blog generator.
   /blog hub + in-depth articles (EN/FR/AR, separate URLs + hreflang).
   Each article: feature image (reuses images/destinations/<img>.jpg when set,
   else a branded SVG banner), category + date meta, multi-section body (or a
   tips list), BlogPosting + (optional FAQ) schema, and a CTA into the funnel
   (flights / rights / eSIM / destinations). Run: node build-blog.cjs */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const STAY22 = "<script>(function(s,t,a,y,o,n){s.Stay22=s.Stay22||{};s.Stay22.params={lmaID:'6a444061c151746f75b1b4ff'};o=t.createElement(a);n=t.getElementsByTagName(a)[0];o.async=1;o.src=y;n.parentNode.insertBefore(o,n);})(window,document,'script','https://scripts.stay22.com/letmeallez.js');</script>";
const PUB = '2026-06-29';

// cat keys: flights / rights / esim / umrah / guide
const ART = [
  {slug:'best-time-to-visit-switzerland', cat:'guide', img:'switzerland', date:'2026-07-02',
   title:{en:'Best Time to Visit Switzerland', fr:'Quelle est la meilleure période pour visiter la Suisse ?', ar:'ما أفضل وقت لزيارة سويسرا؟'},
   desc:{en:'When to visit Switzerland for the Alps, lakes and snow — the best seasons for weather, skiing and lower prices.', fr:'Quand visiter la Suisse pour les Alpes, les lacs et la neige — les meilleures saisons pour la météo, le ski et les prix.', ar:'متى تزور سويسرا للجبال والبحيرات والثلج — أفضل المواسم للطقس والتزلّج والأسعار الأقل.'},
   lead:{en:'Switzerland is stunning all year, but the best time depends on what you want — summer lakes and hiking, or winter snow and skiing. Here’s how to choose, and how to keep the cost down.', fr:'La Suisse est magnifique toute l’année, mais la meilleure période dépend de ce que vous cherchez — les lacs et la randonnée en été, ou la neige et le ski en hiver. Voici comment choisir et maîtriser le budget.', ar:'سويسرا رائعة طوال العام، لكن أفضل وقت يعتمد على ما تريده — البحيرات والمشي في الصيف، أو الثلج والتزلّج في الشتاء. وإليك كيف تختار وكيف تخفّض التكلفة.'},
   tipsH:{en:'When to go', fr:'Quand partir', ar:'متى تذهب'},
   tips:{en:['Summer (Jun–Sep): the warmest season — perfect for lakes, hiking and green Alpine peaks. Peak crowds and prices.','Winter (Dec–Mar): snow, skiing and cozy chalet villages under winter sun — magical, but book ski resorts early.','Spring & autumn: fewer crowds, milder prices and lovely weather for cities like Zurich, Geneva and Lucerne.','Cheapest: the shoulder months (April–May, October–November) and mid-week flights.','Book flights 4–8 weeks ahead — Zurich (ZRH) and Geneva (GVA) are the main gateways.'],
         fr:['Été (juin–sep.) : la saison la plus chaude — idéale pour les lacs, la randonnée et les sommets verdoyants. Foule et prix au plus haut.','Hiver (déc.–mars) : neige, ski et villages de chalets chaleureux sous le soleil d’hiver — magique, mais réservez tôt les stations.','Printemps & automne : moins de monde, prix plus doux et beau temps pour Zurich, Genève et Lucerne.','Le moins cher : les mois intermédiaires (avril–mai, octobre–novembre) et les vols en milieu de semaine.','Réservez vos vols 4 à 8 semaines à l’avance — Zurich (ZRH) et Genève (GVA) sont les principales portes d’entrée.'],
         ar:['الصيف (يونيو–سبتمبر): أدفأ موسم — مثالي للبحيرات والمشي والقمم الخضراء. ذروة الزحام والأسعار.','الشتاء (ديسمبر–مارس): ثلج وتزلّج وقرى شاليهات دافئة تحت شمس الشتاء — ساحر، لكن احجز منتجعات التزلّج مبكرًا.','الربيع والخريف: زحام أقل وأسعار ألطف وطقس جميل لمدن مثل زيورخ وجنيف ولوسيرن.','الأرخص: الأشهر الانتقالية (أبريل–مايو، أكتوبر–نوفمبر) ورحلات منتصف الأسبوع.','احجز رحلاتك قبل 4–8 أسابيع — زيورخ (ZRH) وجنيف (GVA) هما البوّابتان الرئيسيتان.']},
   cta:{href:'/destinations/zurich', label:{en:'Explore Zurich & Switzerland →', fr:'Découvrir Zurich et la Suisse →', ar:'استكشف زيورخ وسويسرا →'}, sub:{en:'Best time & live flight prices.', fr:'Meilleure période et prix en direct.', ar:'أفضل وقت وأسعار مباشرة.'}}},
  {slug:'dolomites-travel-guide', cat:'guide', img:'dolomites', date:'2026-07-02',
   title:{en:'The Dolomites: Italy’s Most Beautiful Mountains', fr:'Les Dolomites : les plus belles montagnes d’Italie', ar:'الدولوميت: أجمل جبال إيطاليا'},
   desc:{en:'When to visit the Dolomites, what to see and how to get there — Italy’s alpine wonderland.', fr:'Quand visiter les Dolomites, que voir et comment s’y rendre — le royaume alpin de l’Italie.', ar:'متى تزور الدولوميت، وماذا ترى، وكيف تصل — عالم إيطاليا الجبلي الساحر.'},
   lead:{en:'The Dolomites are a wonderland of jagged peaks, turquoise lakes and cosy chalets in northern Italy. Here’s when to go and what not to miss.', fr:'Les Dolomites sont un royaume de sommets déchiquetés, de lacs turquoise et de chalets chaleureux dans le nord de l’Italie. Voici quand y aller et à ne pas manquer.', ar:'الدولوميت عالم ساحر من القمم المسنّنة والبحيرات الفيروزية والشاليهات الدافئة في شمال إيطاليا. إليك متى تذهب وماذا لا يفوتك.'},
   tipsH:{en:'Plan your trip', fr:'Préparez votre voyage', ar:'خطّط لرحلتك'},
   tips:{en:['Fly into Venice or Verona, then rent a car — the scenery is best on the road.','June–September is ideal for hiking, wildflowers and mirror-lake reflections.','December–March brings snow, skiing and the famous Dolomiti Superski area.','Catch sunrise “alpenglow” — the peaks turn pink and gold. Unforgettable.','Don’t miss Lago di Braies, Tre Cime di Lavaredo and Seceda.'],
         fr:['Rejoignez Venise ou Vérone, puis louez une voiture — les paysages se savourent sur la route.','Juin–septembre : idéal pour la randonnée, les fleurs et les reflets des lacs.','Décembre–mars : neige, ski et le célèbre domaine Dolomiti Superski.','Admirez l’« alpenglow » au lever du soleil — les sommets virent au rose et or.','À ne pas manquer : le lac de Braies, les Tre Cime di Lavaredo et le Seceda.'],
         ar:['تصل من البندقية أو فيرونا، ثم استأجر سيارة — المناظر أجمل على الطريق.','يونيو–سبتمبر مثالي للمشي والأزهار وانعكاسات البحيرات.','ديسمبر–مارس يجلب الثلج والتزلّج ومنطقة دولوميتي سوبرسكي الشهيرة.','شاهد توهّج الشروق — تتحوّل القمم إلى وردي وذهبي. لا يُنسى.','لا يفوتك بحيرة براييس وتري تشيمي دي لافاريدو وسيسيدا.']},
   cta:{href:'/destinations/dolomites', label:{en:'Explore the Dolomites →', fr:'Découvrir les Dolomites →', ar:'استكشف الدولوميت →'}, sub:{en:'Best time & live flight prices.', fr:'Meilleure période et prix en direct.', ar:'أفضل وقت وأسعار مباشرة.'}}},

  {slug:'norway-travel-guide', cat:'guide', img:'norway', date:'2026-07-02',
   title:{en:'Norway Travel Guide: Fjords, Lights & When to Go', fr:'Guide de la Norvège : fjords, aurores et quand partir', ar:'دليل النرويج: المضايق والشفق ومتى تسافر'},
   desc:{en:'The best time to visit Norway for the fjords and northern lights, plus how to plan your trip.', fr:'La meilleure période pour visiter la Norvège — fjords et aurores boréales — et comment planifier.', ar:'أفضل وقت لزيارة النرويج للمضايق والشفق القطبي، وكيف تخطّط لرحلتك.'},
   lead:{en:'Norway is fjords, waterfalls and the northern lights — one of Europe’s most jaw-dropping countries. Here’s when to go and what to see.', fr:'La Norvège, ce sont les fjords, les cascades et les aurores boréales — l’un des pays les plus époustouflants d’Europe. Voici quand partir et que voir.', ar:'النرويج مضايق وشلّالات وشفق قطبي — من أكثر دول أوروبا إبهارًا. إليك متى تذهب وماذا ترى.'},
   tipsH:{en:'Plan your trip', fr:'Préparez votre voyage', ar:'خطّط لرحلتك'},
   tips:{en:['Fly into Oslo, or Bergen for direct access to the fjords.','May–September has long days, green fjords and mild weather.','October–March is northern-lights season — head north (Tromsø) for the best show.','Take a fjord cruise and the Flåm scenic railway — both are bucket-list.','Norway is pricey — book early and self-cater to save.'],
         fr:['Rejoignez Oslo, ou Bergen pour un accès direct aux fjords.','Mai–septembre : longues journées, fjords verdoyants et temps doux.','Octobre–mars : saison des aurores — montez au nord (Tromsø) pour le meilleur spectacle.','Faites une croisière dans un fjord et le train de Flåm — incontournables.','La Norvège est chère — réservez tôt et cuisinez pour économiser.'],
         ar:['تصل من أوسلو، أو بيرغن للوصول المباشر إلى المضايق.','مايو–سبتمبر: أيام طويلة ومضايق خضراء وطقس معتدل.','أكتوبر–مارس موسم الشفق — اتّجه شمالًا (ترومسو) لأفضل مشهد.','قم بجولة بحرية في مضيق وبقطار فلوم — كلاهما من قائمة الأحلام.','النرويج غالية — احجز مبكرًا واطبخ بنفسك للتوفير.']},
   cta:{href:'/destinations/norway', label:{en:'Explore Norway →', fr:'Découvrir la Norvège →', ar:'استكشف النرويج →'}, sub:{en:'Best time & live flight prices.', fr:'Meilleure période et prix en direct.', ar:'أفضل وقت وأسعار مباشرة.'}}},

  {slug:'banff-travel-guide', cat:'guide', img:'banff', date:'2026-07-02',
   title:{en:'Banff & the Canadian Rockies: Travel Guide', fr:'Banff et les Rocheuses canadiennes : guide de voyage', ar:'بانف وجبال روكي الكندية: دليل السفر'},
   desc:{en:'When to visit Banff, its turquoise lakes and mountains, and how to plan your Canadian Rockies trip.', fr:'Quand visiter Banff, ses lacs turquoise et ses montagnes, et comment planifier votre voyage.', ar:'متى تزور بانف وبحيراتها الفيروزية وجبالها، وكيف تخطّط لرحلتك في جبال روكي.'},
   lead:{en:'Banff National Park is the crown jewel of the Canadian Rockies — turquoise lakes, glaciers and towering peaks. Here’s when to go and what to do.', fr:'Le parc national de Banff est le joyau des Rocheuses canadiennes — lacs turquoise, glaciers et sommets vertigineux. Voici quand partir et que faire.', ar:'حديقة بانف الوطنية جوهرة جبال روكي الكندية — بحيرات فيروزية وأنهار جليدية وقمم شاهقة. إليك متى تذهب وماذا تفعل.'},
   tipsH:{en:'Plan your trip', fr:'Préparez votre voyage', ar:'خطّط لرحلتك'},
   tips:{en:['Fly into Calgary (YYC) — it’s about 90 minutes’ drive to Banff.','June–September is best for hiking, canoeing and the iconic blue lakes.','December–March is prime skiing and snowboarding season.','See Lake Louise and Moraine Lake at sunrise, before the crowds.','Watch for wildlife — elk, bears and bighorn sheep along the drives.'],
         fr:['Rejoignez Calgary (YYC) — environ 90 minutes de route jusqu’à Banff.','Juin–septembre : idéal pour la randonnée, le canoë et les lacs bleus.','Décembre–mars : pleine saison de ski et de snowboard.','Voyez les lacs Louise et Moraine au lever du soleil, avant la foule.','Guettez la faune — wapitis, ours et mouflons le long des routes.'],
         ar:['تصل من كالغاري (YYC) — نحو 90 دقيقة بالسيارة إلى بانف.','يونيو–سبتمبر الأفضل للمشي والتجديف والبحيرات الزرقاء.','ديسمبر–مارس موسم التزلّج الرئيسي.','شاهد بحيرتي لويز ومورين عند الشروق قبل الزحام.','راقب الحياة البرّية — الأيائل والدببة على طول الطرق.']},
   cta:{href:'/destinations/banff', label:{en:'Explore Banff →', fr:'Découvrir Banff →', ar:'استكشف بانف →'}, sub:{en:'Best time & live flight prices.', fr:'Meilleure période et prix en direct.', ar:'أفضل وقت وأسعار مباشرة.'}}},

  {slug:'best-time-to-visit-austria', cat:'guide', img:'austria', date:'2026-07-02',
   title:{en:'Best Time to Visit Austria', fr:'Quelle est la meilleure période pour visiter l’Autriche ?', ar:'ما أفضل وقت لزيارة النمسا؟'},
   desc:{en:'When to visit Austria for the Alps, lakes and imperial cities — the best seasons for weather and skiing.', fr:'Quand visiter l’Autriche pour les Alpes, les lacs et les villes impériales — les meilleures saisons.', ar:'متى تزور النمسا للجبال والبحيرات والمدن الإمبراطورية — أفضل المواسم.'},
   lead:{en:'Austria blends imperial Vienna and Salzburg with fairytale alpine villages and endless mountains. Here’s the best time to go.', fr:'L’Autriche mêle la Vienne impériale et Salzbourg à des villages alpins de conte et des montagnes infinies. Voici la meilleure période.', ar:'النمسا تمزج بين فيينا الإمبراطورية وسالزبورغ وقرى ألبية خرافية وجبال لا تنتهي. إليك أفضل وقت للزيارة.'},
   tipsH:{en:'When to go', fr:'Quand partir', ar:'متى تذهب'},
   tips:{en:['Fly into Vienna or Salzburg — both are easy gateways.','May–September is best for lakes, hiking and the cities.','December–March brings snow, skiing and magical Christmas markets.','Don’t miss Hallstatt, the storybook lakeside village.','Base in Salzburg for the Alps, Vienna for culture and cafés.'],
         fr:['Rejoignez Vienne ou Salzbourg — deux portes d’entrée faciles.','Mai–septembre : idéal pour les lacs, la randonnée et les villes.','Décembre–mars : neige, ski et marchés de Noël magiques.','À ne pas manquer : Hallstatt, le village de conte au bord du lac.','Basez-vous à Salzbourg pour les Alpes, à Vienne pour la culture et les cafés.'],
         ar:['تصل من فيينا أو سالزبورغ — بوّابتان سهلتان.','مايو–سبتمبر الأفضل للبحيرات والمشي والمدن.','ديسمبر–مارس يجلب الثلج والتزلّج وأسواق الميلاد الساحرة.','لا يفوتك هالشتات، القرية الخرافية على ضفاف البحيرة.','اتّخذ سالزبورغ قاعدة للألب، وفيينا للثقافة والمقاهي.']},
   cta:{href:'/destinations/austria', label:{en:'Explore Austria →', fr:'Découvrir l’Autriche →', ar:'استكشف النمسا →'}, sub:{en:'Best time & live flight prices.', fr:'Meilleure période et prix en direct.', ar:'أفضل وقت وأسعار مباشرة.'}}},

  {slug:'cheapest-time-to-book-flights-from-morocco', cat:'flights', img:'istanbul', date:PUB,
   title:{en:'When Is the Cheapest Time to Book Flights from Morocco?', fr:'Quand réserver les vols les moins chers depuis le Maroc ?', ar:'متى تحجز أرخص الرحلات من المغرب؟'},
   desc:{en:'How far ahead to book, the cheapest days to fly, and the seasons to avoid for the lowest prices from Morocco.', fr:'À quel moment réserver, les jours les moins chers pour voler et les saisons à éviter pour les meilleurs tarifs depuis le Maroc.', ar:'متى تحجز، وأرخص الأيام للسفر، والمواسم التي يُفضّل تجنّبها للحصول على أقل الأسعار من المغرب.'},
   lead:{en:'Flight prices from Morocco swing a lot depending on when you book and when you fly. Get the timing right and the same seat can cost far less — here’s what actually moves the price.', fr:'Les prix des vols depuis le Maroc varient beaucoup selon le moment où vous réservez et où vous partez. Avec le bon timing, le même siège coûte bien moins cher — voici ce qui fait vraiment bouger le prix.', ar:'تتقلّب أسعار الرحلات من المغرب كثيرًا حسب وقت الحجز ووقت السفر. مع التوقيت الصحيح، قد يكلّف المقعد نفسه أقل بكثير — وإليك ما يحرّك السعر فعلًا.'},
   secs:[
     {h:{en:'Book 4–8 weeks ahead for international flights', fr:'Réservez 4 à 8 semaines à l’avance pour l’international', ar:'احجز قبل 4–8 أسابيع للرحلات الدولية'},
      p:{en:'For Morocco–Europe and Gulf routes, the sweet spot is usually four to eight weeks before departure. Last-minute almost always costs more, and booking six months out rarely beats it. For domestic hops, two to three weeks is plenty.', fr:'Pour les lignes Maroc–Europe et Golfe, la fenêtre idéale se situe généralement entre quatre et huit semaines avant le départ. La dernière minute coûte presque toujours plus cher, et réserver six mois à l’avance fait rarement mieux. Pour les vols intérieurs, deux à trois semaines suffisent.', ar:'في خطوط المغرب–أوروبا والخليج، تكون الفترة المثالية عادةً من أربعة إلى ثمانية أسابيع قبل المغادرة. الحجز في اللحظة الأخيرة أغلى دائمًا تقريبًا، والحجز قبل ستة أشهر نادرًا ما يكون أفضل. أما الرحلات الداخلية فيكفيها أسبوعان إلى ثلاثة.'}},
     {h:{en:'Fly mid-week, avoid weekends and holidays', fr:'Volez en milieu de semaine, évitez week-ends et fêtes', ar:'سافر منتصف الأسبوع، وتجنّب العطل ونهايات الأسبوع'},
      p:{en:'Tuesday and Wednesday departures are typically cheapest; Friday and Sunday the priciest. Prices also spike hard around summer (June–August) and Eid, when the diaspora travels. Shifting your dates by even a few days often saves real money.', fr:'Les départs du mardi et du mercredi sont en général les moins chers ; le vendredi et le dimanche les plus chers. Les prix grimpent aussi fortement l’été (juin–août) et pendant l’Aïd, quand la diaspora voyage. Décaler vos dates de quelques jours suffit souvent à économiser.', ar:'عادةً ما تكون رحلات الثلاثاء والأربعاء الأرخص، والجمعة والأحد الأغلى. كما ترتفع الأسعار بشدّة في الصيف (يونيو–أغسطس) وفي العيد حين تسافر الجالية. وغالبًا ما يوفّر تغيير تواريخك بأيام قليلة مبلغًا حقيقيًا.'}},
     {h:{en:'Be flexible and compare everything', fr:'Soyez flexible et comparez tout', ar:'كن مرنًا وقارن كل شيء'},
      p:{en:'One search that compares hundreds of airlines and agencies side by side beats checking one airline at a time. Flexible dates, nearby airports (Casablanca vs Rabat, Tangier vs Nador) and one-way combinations can all cut the total.', fr:'Une seule recherche qui compare des centaines de compagnies et d’agences côte à côte vaut mieux que de vérifier une compagnie à la fois. Dates flexibles, aéroports proches (Casablanca ou Rabat, Tanger ou Nador) et combinaisons aller simple peuvent tous réduire la facture.', ar:'بحث واحد يقارن مئات الشركات والوكالات جنبًا إلى جنب أفضل من فحص شركة تلو الأخرى. المرونة في التواريخ، والمطارات القريبة (الدار البيضاء أو الرباط، طنجة أو الناظور)، وتركيبات الذهاب فقط — كلها قد تخفّض الإجمالي.'}},
   ],
   cta:{href:'/flights/', label:{en:'Compare flights from Morocco →', fr:'Comparer les vols depuis le Maroc →', ar:'قارن الرحلات من المغرب →'}, sub:{en:'Live prices, cheapest first.', fr:'Tarifs en direct, les moins chers d’abord.', ar:'أسعار مباشرة، الأرخص أولًا.'}}},

  {slug:'10-tips-to-find-cheap-flights-from-morocco', cat:'flights', img:'paris', date:PUB,
   title:{en:'10 Tips to Find Cheap Flights from Morocco', fr:'10 astuces pour trouver des vols pas chers depuis le Maroc', ar:'10 نصائح للعثور على رحلات رخيصة من المغرب'},
   desc:{en:'Ten habits that consistently lower the price of flights from Morocco — from timing to nearby airports.', fr:'Dix habitudes qui réduisent durablement le prix des vols depuis le Maroc — du timing aux aéroports proches.', ar:'عشر عادات تخفّض باستمرار سعر الرحلات من المغرب — من التوقيت إلى المطارات القريبة.'},
   lead:{en:'Finding a cheap flight isn’t luck — it’s a handful of habits. Here are ten that consistently lower the price of flights from Morocco.', fr:'Trouver un tarif bas n’est pas une question de chance — c’est une poignée d’habitudes. En voici dix qui réduisent régulièrement le prix des vols depuis le Maroc.', ar:'العثور على سعر رخيص ليس حظًّا — بل مجموعة عادات. إليك عشرًا منها تخفّض باستمرار سعر الرحلات من المغرب.'},
   tipsH:{en:'The ten tips', fr:'Les dix astuces', ar:'النصائح العشر'},
   tips:{en:['Compare every airline in one search, not one site at a time','Set your dates to mid-week (Tue/Wed)','Book 4–8 weeks ahead for international routes','Travel outside summer and Eid when you can','Check nearby airports — Casablanca, Rabat, Tangier, Agadir, Fes','Consider one-way tickets on two different airlines','Clear filters and sort cheapest-first','Be ready to book — the best prices don’t last','Travel light to avoid checked-baggage fees','Know your rights if a flight is delayed or cancelled'],
         fr:['Comparez toutes les compagnies en une recherche, pas une par une','Choisissez des dates en milieu de semaine (mar./mer.)','Réservez 4 à 8 semaines à l’avance pour l’international','Voyagez hors été et Aïd quand c’est possible','Vérifiez les aéroports proches — Casablanca, Rabat, Tanger, Agadir, Fès','Envisagez deux allers simples sur deux compagnies','Effacez les filtres et triez du moins cher au plus cher','Soyez prêt à réserver — les meilleurs tarifs ne durent pas','Voyagez léger pour éviter les frais de bagage en soute','Connaissez vos droits en cas de vol retardé ou annulé'],
         ar:['قارن كل الشركات في بحث واحد، لا واحدة تلو الأخرى','اختر تواريخ في منتصف الأسبوع (الثلاثاء/الأربعاء)','احجز قبل 4–8 أسابيع للرحلات الدولية','سافر خارج الصيف والعيد متى أمكن','تحقّق من المطارات القريبة — الدار البيضاء، الرباط، طنجة، أكادير، فاس','فكّر في تذكرتي ذهاب فقط على شركتين مختلفتين','امسح الفلاتر ورتّب من الأرخص إلى الأغلى','كن مستعدًّا للحجز — أفضل الأسعار لا تدوم','سافر بأمتعة خفيفة لتجنّب رسوم الحقائب','اعرف حقوقك إذا تأخرت رحلتك أو أُلغيت']},
   cta:{href:'/flights/', label:{en:'Find your cheapest route →', fr:'Trouvez votre trajet le moins cher →', ar:'اعثر على أرخص رحلاتك →'}, sub:{en:'Compare hundreds of airlines in one search.', fr:'Comparez des centaines de compagnies en une recherche.', ar:'قارن مئات الشركات في بحث واحد.'}}},

  {slug:'flight-delay-compensation-morocco-ec261', cat:'rights', img:'', date:PUB,
   title:{en:'Flight Delayed or Cancelled? Know Your EC 261 Rights', fr:'Vol retardé ou annulé ? Connaissez vos droits (EC 261)', ar:'رحلة متأخرة أو ملغاة؟ اعرف حقوقك (EC 261)'},
   desc:{en:'How much you can claim for a delayed, cancelled or overbooked flight under EU law — and when it covers Morocco flights.', fr:'Combien réclamer pour un vol retardé, annulé ou surréservé selon la loi européenne — et quand cela couvre les vols du Maroc.', ar:'كم يمكنك المطالبة به عن رحلة متأخرة أو ملغاة أو متجاوزة الحجز بموجب القانون الأوروبي — ومتى يشمل ذلك رحلات المغرب.'},
   lead:{en:'Most travellers never claim the money airlines owe them. If your flight was delayed, cancelled or overbooked, EU regulation EC 261 may entitle you to up to €600 — including on many flights to and from Morocco.', fr:'La plupart des voyageurs ne réclament jamais l’argent que leur doivent les compagnies. Si votre vol a été retardé, annulé ou surréservé, le règlement européen EC 261 peut vous donner droit à 600 € — y compris sur de nombreux vols de et vers le Maroc.', ar:'معظم المسافرين لا يطالبون أبدًا بالأموال التي تدين بها لهم شركات الطيران. إذا تأخرت رحلتك أو أُلغيت أو تعرّضت لتجاوز الحجز، فقد يمنحك قانون الاتحاد الأوروبي EC 261 حقًّا في ما يصل إلى 600 يورو — بما في ذلك كثير من رحلات المغرب.'},
   secs:[
     {h:{en:'What EC 261 covers', fr:'Ce que couvre EC 261', ar:'ما يشمله قانون EC 261'},
      p:{en:'EC 261 entitles passengers to between €250 and €600 for long delays (3+ hours), cancellations with short notice, and being denied boarding due to overbooking — when the airline is at fault. The exact amount depends on the flight distance.', fr:'EC 261 donne droit à une indemnité de 250 à 600 € pour les longs retards (3 h ou plus), les annulations à court préavis et le refus d’embarquement pour surréservation — lorsque la compagnie est responsable. Le montant exact dépend de la distance du vol.', ar:'يمنح قانون EC 261 الركّاب تعويضًا من 250 إلى 600 يورو عن التأخّر الطويل (3 ساعات أو أكثر)، والإلغاء بإشعار قصير، والمنع من الصعود بسبب تجاوز الحجز — عندما تكون الشركة مسؤولة. ويعتمد المبلغ على مسافة الرحلة.'}},
     {h:{en:'Does it apply to Morocco flights?', fr:'Cela s’applique-t-il aux vols du Maroc ?', ar:'هل ينطبق على رحلات المغرب؟'},
      p:{en:'It covers any flight departing an EU or UK airport on any airline, and flights arriving in Europe on a European airline. So a Casablanca–Paris on a European carrier is often covered, while a domestic flight or a Gulf route usually isn’t.', fr:'Il couvre tout vol au départ d’un aéroport de l’UE ou du Royaume-Uni, quelle que soit la compagnie, et les vols arrivant en Europe sur une compagnie européenne. Un Casablanca–Paris sur un transporteur européen est donc souvent couvert, contrairement à un vol intérieur ou une ligne du Golfe.', ar:'يشمل أي رحلة تقلع من مطار في الاتحاد الأوروبي أو بريطانيا على أي شركة، والرحلات الواصلة إلى أوروبا على شركة أوروبية. فرحلة الدار البيضاء–باريس على شركة أوروبية غالبًا ما تكون مشمولة، بينما لا تكون الرحلة الداخلية أو خط الخليج عادةً.'}},
     {h:{en:'How to claim — for free', fr:'Comment réclamer — gratuitement', ar:'كيف تطالب — مجانًا'},
      p:{en:'Keep your booking reference and flight number, check eligibility (it takes a couple of minutes and is free), and let a specialist handle the airline and paperwork. It’s no win, no fee — you only pay a success commission if the claim is paid out.', fr:'Conservez votre référence de réservation et votre numéro de vol, vérifiez votre éligibilité (gratuit, deux minutes) et laissez un spécialiste gérer la compagnie et les démarches. Sans gain, sans frais — vous ne payez une commission que si la réclamation aboutit.', ar:'احتفظ برقم الحجز ورقم الرحلة، وتحقّق من الأهلية (مجانًا وفي دقيقتين)، ودع مختصًّا يتولّى التعامل مع الشركة والأوراق. بلا ربح بلا رسوم — لا تدفع عمولة نجاح إلا إذا حصلت على التعويض.'}},
   ],
   cta:{href:'/flight-rights', label:{en:'Know your rights →', fr:'Connaître vos droits →', ar:'اعرف حقوقك →'}, sub:{en:'Free 30-second eligibility check.', fr:'Vérification d’éligibilité gratuite en 30 secondes.', ar:'فحص أهلية مجاني في 30 ثانية.'}}},

  {slug:'travel-esim-vs-roaming', cat:'esim', img:'', date:PUB,
   title:{en:'Travel eSIM vs Roaming: Stay Online Abroad for Less', fr:'eSIM voyage vs itinérance : rester connecté à l’étranger pour moins cher', ar:'eSIM السفر مقابل التجوال: ابقَ متصلًا في الخارج بأقل تكلفة'},
   desc:{en:'What a travel eSIM is, why it beats roaming on price, and how to set one up before you fly.', fr:'Ce qu’est une eSIM voyage, pourquoi elle bat l’itinérance sur le prix, et comment l’installer avant de partir.', ar:'ما هي eSIM السفر، ولماذا تتفوّق على التجوال في السعر، وكيف تجهّزها قبل السفر.'},
   lead:{en:'Coming home to a huge roaming bill is one of travel’s worst surprises. A travel eSIM fixes that: a local data plan you install in minutes, usually for a fraction of roaming.', fr:'Rentrer avec une facture d’itinérance énorme est l’une des pires surprises du voyage. Une eSIM voyage règle le problème : un forfait data local que vous installez en quelques minutes, souvent pour une fraction du prix de l’itinérance.', ar:'العودة إلى فاتورة تجوال ضخمة من أسوأ مفاجآت السفر. تحلّ eSIM السفر هذه المشكلة: باقة بيانات محلية تُركّبها في دقائق، وغالبًا بجزء بسيط من تكلفة التجوال.'},
   secs:[
     {h:{en:'What is a travel eSIM?', fr:'Qu’est-ce qu’une eSIM voyage ?', ar:'ما هي eSIM السفر؟'},
      p:{en:'An eSIM is a digital SIM you install by scanning a QR code — no plastic card. A travel eSIM gives you a local data plan abroad, so you skip expensive roaming and stay online from the moment you land. Your normal number keeps working for calls and texts.', fr:'Une eSIM est une carte SIM numérique que vous installez en scannant un QR code — sans carte plastique. Une eSIM voyage vous donne un forfait data local à l’étranger : vous évitez l’itinérance coûteuse et restez connecté dès l’atterrissage. Votre numéro habituel continue de fonctionner pour les appels et SMS.', ar:'eSIM شريحة رقمية تُركّبها بمسح رمز QR — دون بطاقة بلاستيكية. تمنحك eSIM السفر باقة بيانات محلية في الخارج، فتتجنّب التجوال الباهظ وتبقى متصلًا من لحظة الوصول. ويظلّ رقمك المعتاد يعمل للمكالمات والرسائل.'}},
     {h:{en:'Why it’s cheaper than roaming', fr:'Pourquoi c’est moins cher que l’itinérance', ar:'لماذا هي أرخص من التجوال'},
      p:{en:'Roaming bills your home rate plus a markup for every megabyte abroad. A travel eSIM is a flat local plan you buy upfront, so you know the price before you travel — often a few dollars for a week or more of data, with no bill shock when you get back.', fr:'L’itinérance facture votre tarif domestique majoré pour chaque mégaoctet à l’étranger. Une eSIM voyage est un forfait local fixe acheté d’avance : vous connaissez le prix avant de partir — souvent quelques dollars pour une semaine de data ou plus, sans mauvaise surprise au retour.', ar:'يحاسبك التجوال بسعر بلدك زائد هامش عن كل ميغابايت في الخارج. أما eSIM السفر فهي باقة محلية ثابتة تشتريها مسبقًا، فتعرف السعر قبل السفر — غالبًا بضعة دولارات لأسبوع من البيانات أو أكثر، دون صدمة فاتورة عند العودة.'}},
     {h:{en:'How to set one up', fr:'Comment l’installer', ar:'كيف تجهّزها'},
      p:{en:'Check your phone supports eSIM (most models since 2018 do), pick your destination and a plan, then scan the QR code you receive. Do it at home on Wi-Fi before you fly — it activates automatically when you arrive.', fr:'Vérifiez que votre téléphone gère l’eSIM (la plupart des modèles depuis 2018), choisissez votre destination et un forfait, puis scannez le QR code reçu. Faites-le chez vous en Wi-Fi avant de partir — l’activation se fait automatiquement à l’arrivée.', ar:'تأكّد أن هاتفك يدعم eSIM (معظم الطُرز منذ 2018)، اختر وجهتك وباقة، ثم امسح رمز QR الذي يصلك. افعل ذلك في بيتك عبر Wi-Fi قبل السفر — وتتفعّل تلقائيًا عند الوصول.'}},
   ],
   cta:{href:'/esim', label:{en:'Compare travel eSIMs →', fr:'Comparer les eSIM voyage →', ar:'قارن شرائح eSIM للسفر →'}, sub:{en:'Pick your country, see prices.', fr:'Choisissez votre pays, voyez les prix.', ar:'اختر بلدك، واعرف الأسعار.'}}},

  {slug:'umrah-from-morocco-guide', cat:'umrah', img:'jeddah', date:PUB,
   title:{en:'Umrah from Morocco: Flights, Best Time & Practical Tips', fr:'Omra depuis le Maroc : vols, meilleure période et conseils pratiques', ar:'العمرة من المغرب: الرحلات، أفضل وقت، ونصائح عملية'},
   desc:{en:'How to plan Umrah from Morocco — finding flights to Jeddah, the cheapest seasons, and practical tips for the trip.', fr:'Comment planifier la Omra depuis le Maroc — trouver des vols vers Djeddah, les saisons les moins chères et des conseils pratiques.', ar:'كيف تخطّط للعمرة من المغرب — إيجاد رحلات إلى جدة، وأرخص المواسم، ونصائح عملية للرحلة.'},
   lead:{en:'For many Moroccan travellers, Umrah is the trip of a lifetime — and a little planning keeps the cost down and the journey smooth. Here’s how to handle the flights and timing.', fr:'Pour de nombreux voyageurs marocains, la Omra est le voyage d’une vie — et un peu de planification réduit le coût et facilite le trajet. Voici comment gérer les vols et le timing.', ar:'بالنسبة لكثير من المسافرين المغاربة، العمرة رحلة العمر — وقليل من التخطيط يخفّض التكلفة ويجعل الرحلة سلسة. إليك كيف تتعامل مع الرحلات والتوقيت.'},
   secs:[
     {h:{en:'Flights: Jeddah is the gateway', fr:'Vols : Djeddah est la porte d’entrée', ar:'الرحلات: جدة هي البوابة'},
      p:{en:'Jeddah is the usual arrival point for Umrah, a short drive from Makkah. Direct and one-stop flights run from Casablanca; booking several weeks ahead and comparing every airline in one search gives you the best price. Prices rise sharply in Ramadan and the Hajj season.', fr:'Djeddah est le point d’arrivée habituel pour la Omra, à courte distance de La Mecque. Des vols directs et avec une escale partent de Casablanca ; réserver plusieurs semaines à l’avance et comparer toutes les compagnies en une recherche donne le meilleur tarif. Les prix grimpent fortement pendant le Ramadan et la saison du Hajj.', ar:'جدة هي نقطة الوصول المعتادة للعمرة، وتبعد مسافة قصيرة عن مكة. تنطلق رحلات مباشرة وبتوقّف واحد من الدار البيضاء؛ والحجز قبل أسابيع ومقارنة كل الشركات في بحث واحد يمنحك أفضل سعر. وترتفع الأسعار بشدّة في رمضان وموسم الحج.'}},
     {h:{en:'Best time to go', fr:'Meilleure période', ar:'أفضل وقت للذهاب'},
      p:{en:'Outside Ramadan and Hajj, the cooler months (roughly November to March) are the most comfortable and usually the cheapest for flights. Mid-week departures and flexible dates help further.', fr:'Hors Ramadan et Hajj, les mois plus frais (de novembre à mars environ) sont les plus agréables et généralement les moins chers pour les vols. Les départs en milieu de semaine et des dates flexibles aident encore.', ar:'خارج رمضان والحج، تكون الأشهر الأبرد (تقريبًا من نوفمبر إلى مارس) الأكثر راحة وعادةً الأرخص للرحلات. وتساعد رحلات منتصف الأسبوع والتواريخ المرنة أكثر.'}},
     {h:{en:'Practical tips', fr:'Conseils pratiques', ar:'نصائح عملية'},
      p:{en:'Travel light, keep your documents together, and set up a travel eSIM before you fly so you can stay in touch with family without roaming charges. Confirm entry requirements through official sources before booking.', fr:'Voyagez léger, gardez vos documents ensemble et installez une eSIM voyage avant de partir pour rester en contact avec la famille sans frais d’itinérance. Vérifiez les conditions d’entrée auprès des sources officielles avant de réserver.', ar:'سافر بأمتعة خفيفة، واحتفظ بوثائقك معًا، وجهّز eSIM للسفر قبل المغادرة لتبقى على تواصل مع العائلة دون رسوم تجوال. وتأكّد من متطلّبات الدخول من المصادر الرسمية قبل الحجز.'}},
   ],
   cta:{href:'/flights/casablanca-jeddah', label:{en:'See Casablanca–Jeddah prices →', fr:'Voir les tarifs Casablanca–Djeddah →', ar:'اعرض أسعار الدار البيضاء–جدة →'}, sub:{en:'Live prices, cheapest first.', fr:'Prix en direct, les moins chers d’abord.', ar:'أسعار مباشرة، الأرخص أولًا.'}}},

  {slug:'best-time-to-visit-europe-from-morocco', cat:'guide', img:'barcelona', date:PUB,
   title:{en:'The Best Time to Visit Europe from Morocco', fr:'La meilleure période pour visiter l’Europe depuis le Maroc', ar:'أفضل وقت لزيارة أوروبا من المغرب'},
   desc:{en:'Spring, summer or autumn? When to visit Europe from Morocco for good weather, fewer crowds and cheaper flights.', fr:'Printemps, été ou automne ? Quand visiter l’Europe depuis le Maroc pour le beau temps, moins de foule et des vols moins chers.', ar:'الربيع أم الصيف أم الخريف؟ متى تزور أوروبا من المغرب لطقس جيد وازدحام أقل ورحلات أرخص.'},
   lead:{en:'Europe is a short hop from Morocco, but when you go changes everything — the weather, the crowds and the price of your flight. Here’s how to pick the right window.', fr:'L’Europe est à un saut du Maroc, mais le moment où vous partez change tout — la météo, la foule et le prix de votre vol. Voici comment choisir la bonne fenêtre.', ar:'أوروبا على بُعد قفزة قصيرة من المغرب، لكنّ وقت سفرك يغيّر كل شيء — الطقس، والازدحام، وسعر رحلتك. وإليك كيف تختار النافذة المناسبة.'},
   secs:[
     {h:{en:'Spring and autumn — the sweet spot', fr:'Printemps et automne — la période idéale', ar:'الربيع والخريف — الفترة المثالية'},
      p:{en:'April to June and September to October usually offer the best balance: mild weather, smaller crowds and lower prices than peak summer. Cities like Paris, Barcelona and Rome are at their most pleasant.', fr:'D’avril à juin et de septembre à octobre, on a généralement le meilleur équilibre : temps doux, moins de foule et tarifs plus bas qu’en plein été. Des villes comme Paris, Barcelone et Rome sont alors les plus agréables.', ar:'من أبريل إلى يونيو ومن سبتمبر إلى أكتوبر يكون التوازن عادةً في أفضل حالاته: طقس معتدل، وازدحام أقل، وأسعار أدنى من ذروة الصيف. ومدن مثل باريس وبرشلونة وروما تكون في أجمل أحوالها.'}},
     {h:{en:'Summer — sunny but busy and pricey', fr:'L’été — ensoleillé mais bondé et cher', ar:'الصيف — مشمس لكنه مزدحم وغالٍ'},
      p:{en:'July and August bring the warmest weather and long days, but also the biggest crowds and the highest flight prices — made worse by the diaspora travelling. If you must go in summer, book early and travel mid-week.', fr:'Juillet et août offrent le temps le plus chaud et de longues journées, mais aussi la plus grande foule et les vols les plus chers — accentués par les voyages de la diaspora. Si vous devez partir en été, réservez tôt et voyagez en milieu de semaine.', ar:'يجلب يوليو وأغسطس أدفأ طقس وأيامًا طويلة، لكن أيضًا أكبر زحام وأعلى أسعار للرحلات — ويزيدها سفر الجالية. وإن كان لا بدّ من السفر صيفًا، فاحجز مبكرًا وسافر في منتصف الأسبوع.'}},
     {h:{en:'Winter — deals and quiet cities', fr:'L’hiver — bons plans et villes calmes', ar:'الشتاء — عروض ومدن هادئة'},
      p:{en:'November to March is the cheapest time to fly and the quietest to sightsee. It’s cold and days are short, but city breaks, museums and festive markets shine — and flights are often a fraction of summer prices.', fr:'De novembre à mars, c’est la période la moins chère pour voler et la plus calme pour visiter. Il fait froid et les jours sont courts, mais les city-breaks, musées et marchés de fête brillent — et les tarifs sont souvent une fraction des prix d’été.', ar:'من نوفمبر إلى مارس، يكون الطيران الأرخص والزيارة الأهدأ. الجوّ بارد والأيام قصيرة، لكن العطل المدينية والمتاحف والأسواق الاحتفالية تتألّق — وغالبًا ما تكون الأسعار جزءًا بسيطًا من أسعار الصيف.'}},
   ],
   cta:{href:'/destinations/', label:{en:'Browse destinations →', fr:'Parcourir les destinations →', ar:'تصفّح الوجهات →'}, sub:{en:'Best time & live prices for each city.', fr:'Meilleure période et tarifs en direct par ville.', ar:'أفضل وقت وأسعار مباشرة لكل مدينة.'}}},

  {slug:'hand-luggage-rules-fly-carry-on-only', cat:'guide', img:'', date:PUB,
   title:{en:'Carry-On Only: Hand Luggage Rules & Packing Tips', fr:'Bagage cabine uniquement : règles et astuces de préparation', ar:'حقيبة يد فقط: قواعد الأمتعة ونصائح التحضير'},
   desc:{en:'How to fly carry-on only from Morocco: typical size and liquid rules, what to pack, and how to dodge baggage fees.', fr:'Comment voyager en cabine uniquement depuis le Maroc : tailles et règles sur les liquides, quoi emporter et comment éviter les frais de bagage.', ar:'كيف تسافر بحقيبة يد فقط من المغرب: المقاسات وقواعد السوائل، وماذا تحزم، وكيف تتجنّب رسوم الأمتعة.'},
   lead:{en:'Flying with just a carry-on is faster, cheaper and stress-free — no waiting at the belt, no baggage fees. A little planning makes it easy.', fr:'Voyager avec un seul bagage cabine est plus rapide, moins cher et sans stress — pas d’attente au tapis, pas de frais de bagage. Un peu d’organisation suffit.', ar:'السفر بحقيبة يد فقط أسرع وأرخص وبلا توتّر — لا انتظار عند السير المتحرّك ولا رسوم أمتعة. وقليل من التخطيط يجعله سهلًا.'},
   secs:[
     {h:{en:'Know the size and liquid rules', fr:'Connaissez les règles de taille et de liquides', ar:'اعرف قواعد المقاس والسوائل'},
      p:{en:'Most airlines allow a cabin bag around 55 × 40 × 20 cm, but budget carriers are stricter and may charge for anything bigger than a small under-seat bag — always check your airline before you fly. Liquids must be in containers of 100 ml or less, inside one clear resealable bag.', fr:'La plupart des compagnies acceptent un bagage cabine d’environ 55 × 40 × 20 cm, mais les compagnies low-cost sont plus strictes et font payer tout ce qui dépasse un petit sac sous le siège — vérifiez toujours votre compagnie avant de partir. Les liquides doivent être en contenants de 100 ml maximum, dans un sac transparent refermable.', ar:'تسمح معظم الشركات بحقيبة مقصورة بنحو 55 × 40 × 20 سم، لكن شركات التوفير أكثر صرامة وقد تفرض رسومًا على أي شيء أكبر من حقيبة صغيرة تحت المقعد — تحقّق دائمًا من شركتك قبل السفر. ويجب أن تكون السوائل في عبوات سعة 100 مل أو أقل، داخل كيس شفّاف قابل لإعادة الإغلاق.'}},
     {h:{en:'Pack smart and light', fr:'Préparez malin et léger', ar:'احزم بذكاء وخفّة'},
      p:{en:'Roll clothes to save space, wear your bulkiest items (coat, boots) on the plane, and pack versatile pieces you can mix and match. Keep documents, chargers and any medication in an easy-to-reach pocket.', fr:'Roulez vos vêtements pour gagner de la place, portez vos articles les plus volumineux (manteau, bottes) dans l’avion et emportez des pièces polyvalentes à combiner. Gardez documents, chargeurs et médicaments dans une poche facile d’accès.', ar:'لُفّ الملابس لتوفير المساحة، وارتدِ أضخم القطع (المعطف، الحذاء) في الطائرة، واحزم قطعًا متعدّدة الاستعمال يمكن تنسيقها. واحتفظ بالوثائق والشواحن وأي دواء في جيب سهل الوصول.'}},
     {h:{en:'Dodge the baggage fees', fr:'Évitez les frais de bagage', ar:'تجنّب رسوم الأمتعة'},
      p:{en:'Checked-bag fees can quietly double a cheap ticket. Going carry-on only keeps the price you saw the price you pay. If you do need a checked bag, add it online in advance — it’s almost always cheaper than at the airport.', fr:'Les frais de bagage en soute peuvent discrètement doubler un billet bon marché. Voyager en cabine uniquement garde le prix vu comme le prix payé. Si vous avez besoin d’une soute, ajoutez-la en ligne à l’avance — c’est presque toujours moins cher qu’à l’aéroport.', ar:'قد تضاعف رسوم الحقيبة المسجّلة سعرًا رخيصًا بهدوء. والسفر بحقيبة يد فقط يبقي السعر الذي رأيته هو السعر الذي تدفعه. وإن احتجت حقيبة مسجّلة، فأضفها عبر الإنترنت مسبقًا — فهي أرخص دائمًا تقريبًا من المطار.'}},
   ],
   cta:{href:'/flights/', label:{en:'Find a carry-on price →', fr:'Trouver un tarif cabine →', ar:'ابحث عن سعر بحقيبة يد →'}, sub:{en:'Compare airlines, baggage included.', fr:'Comparez les compagnies, bagage compris.', ar:'قارن الشركات، مع الأمتعة.'}}},

  {slug:'best-time-to-visit-dubai', cat:'guide', img:'dubai', date:'2026-07-01',
   title:{en:'When Is the Best Time to Visit Dubai?', fr:'Quelle est la meilleure période pour visiter Dubaï ?', ar:'ما أفضل وقت لزيارة دبي؟'},
   desc:{en:'The best months for weather and prices, when to avoid the heat, and how to find cheap flights to Dubai.', fr:'Les meilleurs mois pour la météo et les prix, quand éviter la chaleur, et comment trouver des vols pas chers pour Dubaï.', ar:'أفضل الأشهر للطقس والأسعار، ومتى تتجنّب الحرّ، وكيف تجد رحلات رخيصة إلى دبي.'},
   lead:{en:'Dubai is a year-round city, but when you go changes everything — from the weather to what you pay. Here’s how to pick the right time.', fr:'Dubaï se visite toute l’année, mais le moment du voyage change tout — de la météo au prix. Voici comment choisir la bonne période.', ar:'يمكن زيارة دبي طوال العام، لكن توقيت السفر يغيّر كل شيء — من الطقس إلى ما تدفعه. وإليك كيف تختار الوقت المناسب.'},
   tipsH:{en:'When to go', fr:'Quand partir', ar:'متى تذهب'},
   tips:{en:['November to March is peak season: warm, sunny days around 24–30°C, perfect for the beach and outdoor sights.','June to September is very hot (often above 40°C) — flights and hotels are cheapest, but plan indoor activities.','April, May and October are shoulder months: still warm, fewer crowds, and better prices than peak winter.','Avoid major events and holidays (like Eid and the Dubai Shopping Festival) if you want lower hotel rates.','Book flights 4–6 weeks ahead and fly mid-week for the best price.'],
         fr:['De novembre à mars, c’est la haute saison : journées chaudes et ensoleillées de 24 à 30 °C, parfaites pour la plage et les visites.','De juin à septembre, il fait très chaud (souvent plus de 40 °C) — vols et hôtels au plus bas, mais prévoyez des activités en intérieur.','Avril, mai et octobre sont des mois intermédiaires : encore chauds, moins de monde et de meilleurs prix qu’en plein hiver.','Évitez les grands événements et fêtes (Aïd, Dubai Shopping Festival) pour des tarifs d’hôtel plus bas.','Réservez vos vols 4 à 6 semaines à l’avance et partez en milieu de semaine pour le meilleur prix.'],
         ar:['من نوفمبر إلى مارس هو الموسم الأعلى: أيام دافئة ومشمسة بين 24 و30 °م، مثالية للشاطئ والمعالم الخارجية.','من يونيو إلى سبتمبر حارّ جدًّا (غالبًا فوق 40 °م) — الرحلات والفنادق الأرخص، لكن خطّط لأنشطة داخلية.','أبريل ومايو وأكتوبر أشهر انتقالية: لا تزال دافئة، وزحام أقل، وأسعار أفضل من ذروة الشتاء.','تجنّب الفعاليات والأعياد الكبرى (العيد، مهرجان دبي للتسوّق) إن أردت أسعار فنادق أقل.','احجز رحلاتك قبل 4–6 أسابيع وسافر منتصف الأسبوع للحصول على أفضل سعر.']},
   cta:{href:'/flights/casablanca-dubai', label:{en:'Find flights to Dubai →', fr:'Trouver des vols pour Dubaï →', ar:'ابحث عن رحلات إلى دبي →'}, sub:{en:'Live prices, cheapest first.', fr:'Prix en direct, les moins chers d’abord.', ar:'أسعار مباشرة، الأرخص أولًا.'}}},

  {slug:'how-to-find-cheap-hotels', cat:'guide', img:'rome', date:'2026-07-01',
   title:{en:'How to Find Cheap Hotels Anywhere', fr:'Comment trouver des hôtels pas chers partout', ar:'كيف تجد فنادق رخيصة في أي مكان'},
   desc:{en:'Simple, proven ways to pay less for the same hotel room — from comparing sites to booking at the right time.', fr:'Des méthodes simples et éprouvées pour payer moins la même chambre — de la comparaison des sites au bon moment pour réserver.', ar:'طرق بسيطة ومجرّبة لدفع أقل مقابل نفس الغرفة — من مقارنة المواقع إلى الحجز في الوقت المناسب.'},
   lead:{en:'The same room often sells at very different prices depending on where and when you book. A few habits can save you a lot.', fr:'La même chambre se vend souvent à des prix très différents selon où et quand vous réservez. Quelques habitudes peuvent vous faire économiser beaucoup.', ar:'تُباع الغرفة نفسها غالبًا بأسعار مختلفة جدًّا حسب مكان ووقت الحجز. وبضع عادات قد توفّر عليك الكثير.'},
   tipsH:{en:'How to pay less', fr:'Comment payer moins', ar:'كيف تدفع أقل'},
   tips:{en:['Compare across booking sites in one search instead of trusting a single platform — prices for the same room vary a lot.','Be flexible with dates; mid-week nights and the off-season are usually cheaper.','Book a few weeks ahead, but check again close to your stay — last-minute deals appear when hotels want to fill rooms.','Look slightly outside the city centre and check transport links; you often get more for your money.','Read recent reviews for cleanliness, location and hidden fees before you book.'],
         fr:['Comparez les sites de réservation en une seule recherche plutôt que de vous fier à une seule plateforme — les prix de la même chambre varient beaucoup.','Soyez flexible sur les dates ; les nuits en milieu de semaine et la basse saison sont généralement moins chères.','Réservez quelques semaines à l’avance, mais revérifiez à l’approche du séjour — des offres de dernière minute apparaissent quand les hôtels veulent remplir.','Regardez un peu en dehors du centre et vérifiez les transports ; vous en avez souvent plus pour votre argent.','Lisez les avis récents (propreté, emplacement, frais cachés) avant de réserver.'],
         ar:['قارن بين مواقع الحجز في بحث واحد بدل الاعتماد على منصّة واحدة — تتفاوت أسعار الغرفة نفسها كثيرًا.','كن مرنًا في التواريخ؛ ليالي منتصف الأسبوع والموسم المنخفض أرخص عادةً.','احجز قبل أسابيع، لكن تحقّق مجدّدًا قرب موعدك — تظهر عروض اللحظة الأخيرة حين تريد الفنادق ملء غرفها.','ابحث قليلًا خارج وسط المدينة وتحقّق من وسائل النقل؛ غالبًا تحصل على أكثر مقابل مالك.','اقرأ المراجعات الحديثة (النظافة، الموقع، الرسوم الخفية) قبل الحجز.']},
   cta:{href:'/hotels', label:{en:'Compare hotel prices →', fr:'Comparer les prix des hôtels →', ar:'قارن أسعار الفنادق →'}, sub:{en:'Hundreds of sites, best deal first.', fr:'Des centaines de sites, la meilleure offre d’abord.', ar:'مئات المواقع، أفضل عرض أولًا.'}}},

  {slug:'how-to-set-up-a-travel-esim', cat:'esim', img:'', date:'2026-07-01',
   title:{en:'How to Set Up a Travel eSIM (Step by Step)', fr:'Comment configurer une eSIM de voyage (étape par étape)', ar:'كيف تُفعّل شريحة eSIM للسفر (خطوة بخطوة)'},
   desc:{en:'A simple guide to buying, installing and activating a travel eSIM so you’re online the moment you land.', fr:'Un guide simple pour acheter, installer et activer une eSIM de voyage afin d’être connecté dès l’atterrissage.', ar:'دليل بسيط لشراء شريحة eSIM للسفر وتثبيتها وتفعيلها لتكون متّصلًا فور هبوطك.'},
   lead:{en:'An eSIM gives you mobile data abroad without swapping your physical SIM or paying roaming. Setup takes a few minutes — here’s how.', fr:'Une eSIM vous donne des données mobiles à l’étranger sans changer votre carte SIM ni payer l’itinérance. L’installation prend quelques minutes — voici comment.', ar:'تمنحك eSIM بيانات هاتفية في الخارج دون تبديل شريحتك أو دفع رسوم التجوال. والإعداد يستغرق دقائق — وإليك الطريقة.'},
   tipsH:{en:'The steps', fr:'Les étapes', ar:'الخطوات'},
   tips:{en:['Check your phone supports eSIM (most recent iPhones and Android flagships do) and is carrier-unlocked.','Pick your destination and compare providers for the best plan size and price before you travel.','Buy the plan online; you’ll get a QR code by email or in the provider’s app.','Install it before you fly: scan the QR code in your phone’s mobile-data settings while on Wi-Fi.','On arrival, switch the eSIM on for data and keep your normal SIM for calls and your number.','Turn off data roaming on your home SIM so you’re never charged by accident.'],
         fr:['Vérifiez que votre téléphone gère l’eSIM (la plupart des iPhones récents et smartphones Android haut de gamme) et qu’il est désimlocké.','Choisissez votre destination et comparez les fournisseurs pour la meilleure taille de forfait et le meilleur prix avant de partir.','Achetez le forfait en ligne ; vous recevrez un QR code par e-mail ou dans l’application du fournisseur.','Installez-le avant de partir : scannez le QR code dans les réglages de données mobiles, connecté en Wi-Fi.','À l’arrivée, activez l’eSIM pour les données et gardez votre SIM habituelle pour les appels et votre numéro.','Désactivez l’itinérance des données sur votre SIM d’origine pour ne jamais être facturé par erreur.'],
         ar:['تأكّد أن هاتفك يدعم eSIM (معظم أجهزة آيفون الحديثة وهواتف أندرويد الرائدة) وأنه غير مقفل على شركة.','اختر وجهتك وقارن المزوّدين لأفضل حجم باقة وسعر قبل السفر.','اشترِ الباقة عبر الإنترنت؛ ستصلك رمز QR بالبريد أو في تطبيق المزوّد.','ثبّتها قبل السفر: امسح رمز QR في إعدادات بيانات الهاتف وأنت متّصل بالـ Wi-Fi.','عند الوصول، فعّل eSIM للبيانات واحتفظ بشريحتك المعتادة للمكالمات ورقمك.','أوقف تجوال البيانات على شريحتك الأصلية كي لا تُحاسَب بالخطأ.']},
   cta:{href:'/esim', label:{en:'Compare travel eSIMs →', fr:'Comparer les eSIM de voyage →', ar:'قارن شرائح eSIM للسفر →'}, sub:{en:'Top providers, cheapest first.', fr:'Meilleurs fournisseurs, les moins chers d’abord.', ar:'أفضل المزوّدين، الأرخص أولًا.'}}},

  {slug:'what-to-do-if-your-flight-is-cancelled', cat:'rights', img:'', date:'2026-07-01',
   title:{en:'What to Do if Your Flight Is Cancelled', fr:'Que faire si votre vol est annulé', ar:'ماذا تفعل إذا أُلغيت رحلتك'},
   desc:{en:'Your rights when a flight is cancelled, how to get rebooked or refunded, and when you can claim compensation.', fr:'Vos droits en cas d’annulation de vol, comment être réacheminé ou remboursé, et quand réclamer une indemnisation.', ar:'حقوقك عند إلغاء رحلتك، وكيف تُعاد جدولتك أو تُسترد أموالك، ومتى يمكنك المطالبة بتعويض.'},
   lead:{en:'A cancelled flight is stressful, but you have clear rights. Acting calmly and knowing what to ask for can save your trip — and money.', fr:'Un vol annulé est stressant, mais vous avez des droits clairs. Agir calmement et savoir quoi demander peut sauver votre voyage — et votre argent.', ar:'إلغاء الرحلة مرهق، لكن لديك حقوق واضحة. والتصرّف بهدوء ومعرفة ما تطلبه قد ينقذ رحلتك — وأموالك.'},
   tipsH:{en:'Step by step', fr:'Étape par étape', ar:'خطوة بخطوة'},
   tips:{en:['Ask the airline for a free rebooking on the next available flight, or a full refund if you no longer want to travel.','For long waits, you’re usually owed care — meals, drinks and a hotel if you’re stranded overnight.','Keep every document: booking, boarding pass, the cancellation notice and any receipts for expenses.','On flights from the EU (or EU airlines), you may be owed up to €600 if it was the airline’s fault and you were told late.','Don’t accept vouchers if you’d rather have cash — you can usually insist on a refund to your card.','If the airline refuses a valid claim, a service like AirHelp can pursue it for you.'],
         fr:['Demandez à la compagnie un réacheminement gratuit sur le prochain vol disponible, ou un remboursement intégral si vous ne voulez plus voyager.','En cas de longue attente, on vous doit généralement une prise en charge — repas, boissons et hôtel si vous êtes bloqué la nuit.','Conservez chaque document : réservation, carte d’embarquement, avis d’annulation et tout reçu de dépenses.','Sur les vols au départ de l’UE (ou des compagnies de l’UE), vous pouvez avoir droit à jusqu’à 600 € si la compagnie est en faute et vous a prévenu tard.','N’acceptez pas de bons si vous préférez l’argent — vous pouvez généralement exiger un remboursement sur votre carte.','Si la compagnie refuse une demande valable, un service comme AirHelp peut la traiter pour vous.'],
         ar:['اطلب من الشركة إعادة حجز مجّانية على أقرب رحلة متاحة، أو استردادًا كاملًا إن لم تعد ترغب في السفر.','عند الانتظار الطويل، تستحقّ عادةً رعاية — وجبات ومشروبات وفندقًا إن علقت ليلًا.','احتفظ بكل وثيقة: الحجز، بطاقة الصعود، إشعار الإلغاء، وأي إيصالات للنفقات.','في الرحلات المغادرة من الاتحاد الأوروبي (أو شركات أوروبية)، قد تستحقّ حتى 600 يورو إذا كان الخطأ من الشركة وأُبلغت متأخّرًا.','لا تقبل قسائم إن كنت تفضّل المال — يمكنك عادةً الإصرار على استرداد إلى بطاقتك.','إذا رفضت الشركة مطالبة صحيحة، فيمكن لخدمة مثل AirHelp متابعتها نيابةً عنك.']},
   cta:{href:'/compensation', label:{en:'Check if you’re owed →', fr:'Vérifiez si l’on vous doit →', ar:'تحقّق ممّا إن كان لك تعويض →'}, sub:{en:'Up to €600 — free check.', fr:'Jusqu’à 600 € — vérification gratuite.', ar:'حتى 600 يورو — فحص مجّاني.'}}},

  {slug:'how-to-avoid-jet-lag', cat:'guide', img:'tokyo', date:'2026-07-01',
   title:{en:'How to Avoid Jet Lag: A Practical Guide', fr:'Comment éviter le décalage horaire : guide pratique', ar:'كيف تتجنّب اضطراب الرحلات الجوية: دليل عملي'},
   desc:{en:'Simple, science-backed ways to beat jet lag on long flights — before, during and after you fly.', fr:'Des méthodes simples et fondées sur la science pour vaincre le décalage horaire — avant, pendant et après le vol.', ar:'طرق بسيطة ومدعومة علميًّا للتغلّب على اضطراب الرحلات في الطيران الطويل — قبل السفر وأثناءه وبعده.'},
   lead:{en:'Crossing time zones throws off your body clock, but a few habits help you adjust faster and enjoy your trip from day one.', fr:'Traverser les fuseaux horaires dérègle votre horloge interne, mais quelques habitudes aident à vous adapter plus vite et à profiter dès le premier jour.', ar:'عبور المناطق الزمنية يُربك ساعتك البيولوجية، لكن بضع عادات تساعدك على التأقلم أسرع والاستمتاع برحلتك من اليوم الأول.'},
   tipsH:{en:'Beat the jet lag', fr:'Vaincre le décalage', ar:'تغلّب على الاضطراب'},
   tips:{en:['A few days before you fly, shift your sleep an hour earlier or later toward your destination’s time.','Set your watch to the destination time as soon as you board, and sleep or stay awake accordingly.','Drink plenty of water and go easy on coffee and alcohol — both worsen jet lag.','Get daylight when you arrive; sunlight is the fastest way to reset your body clock.','Resist long naps on the first day — push through to a normal local bedtime.'],
         fr:['Quelques jours avant le départ, décalez votre sommeil d’une heure plus tôt ou plus tard vers l’heure de destination.','Réglez votre montre à l’heure de destination dès l’embarquement, et dormez ou restez éveillé en conséquence.','Buvez beaucoup d’eau et limitez café et alcool — les deux aggravent le décalage.','Exposez-vous à la lumière du jour à l’arrivée ; le soleil est le moyen le plus rapide de réinitialiser l’horloge interne.','Évitez les longues siestes le premier jour — tenez jusqu’à une heure de coucher locale normale.'],
         ar:['قبل السفر بأيام، أزِح نومك ساعة أبكر أو أمتأخّر باتجاه توقيت وجهتك.','اضبط ساعتك على توقيت الوجهة فور الصعود، ونم أو ابقَ مستيقظًا تبعًا لذلك.','اشرب الماء بكثرة وقلّل القهوة والكحول — كلاهما يزيد الاضطراب.','تعرّض لضوء النهار عند الوصول؛ الشمس أسرع وسيلة لإعادة ضبط ساعتك البيولوجية.','تجنّب القيلولة الطويلة في اليوم الأول — اصمد حتى موعد نوم محلّي طبيعي.']},
   cta:{href:'/flights/', label:{en:'Find a long-haul flight →', fr:'Trouver un vol long-courrier →', ar:'ابحث عن رحلة طويلة →'}, sub:{en:'Compare airlines in one search.', fr:'Comparez les compagnies en une recherche.', ar:'قارن الشركات في بحث واحد.'}}},

  {slug:'best-time-to-book-hotels', cat:'guide', img:'london', date:'2026-07-01',
   title:{en:'When Is the Best Time to Book a Hotel?', fr:'Quel est le meilleur moment pour réserver un hôtel ?', ar:'ما أفضل وقت لحجز فندق؟'},
   desc:{en:'How far ahead to book a hotel, when prices drop, and how to avoid overpaying for your stay.', fr:'À quel moment réserver un hôtel, quand les prix baissent, et comment éviter de payer trop cher.', ar:'متى تحجز فندقًا، ومتى تنخفض الأسعار، وكيف تتجنّب الدفع الزائد لإقامتك.'},
   lead:{en:'Hotel prices move with demand, just like flights. Timing your booking right can mean the same room for a lot less.', fr:'Les prix des hôtels varient avec la demande, comme les vols. Bien choisir le moment de réserver, c’est la même chambre pour bien moins.', ar:'تتحرّك أسعار الفنادق مع الطلب، تمامًا كالرحلات. وضبط توقيت حجزك قد يعني الغرفة نفسها بسعر أقل بكثير.'},
   tipsH:{en:'Time it right', fr:'Le bon timing', ar:'اضبط التوقيت'},
   tips:{en:['For popular city breaks, booking a few weeks ahead usually gives a good balance of choice and price.','For peak season or big events, book early — prices only climb as rooms sell out.','For flexible trips, last-minute can win: hotels drop prices to fill empty rooms a day or two before.','Always choose a free-cancellation rate when you can, then rebook if the price drops later.','Mid-week stays and the shoulder season are almost always cheaper than weekends and high season.'],
         fr:['Pour les city breaks populaires, réserver quelques semaines à l’avance offre un bon équilibre entre choix et prix.','En haute saison ou pour de grands événements, réservez tôt — les prix ne font que monter à mesure que les chambres partent.','Pour les voyages flexibles, la dernière minute peut payer : les hôtels baissent les prix pour remplir un ou deux jours avant.','Choisissez toujours un tarif annulable gratuitement si possible, puis re-réservez si le prix baisse.','Les séjours en milieu de semaine et en saison intermédiaire sont presque toujours moins chers que les week-ends et la haute saison.'],
         ar:['لرحلات المدن الشائعة، الحجز قبل أسابيع يمنح توازنًا جيّدًا بين الخيار والسعر.','في الموسم الأعلى أو الفعاليات الكبرى، احجز مبكرًا — الأسعار ترتفع كلّما نفدت الغرف.','للرحلات المرنة، قد تربح اللحظة الأخيرة: تخفّض الفنادق الأسعار لملء الغرف قبل يوم أو يومين.','اختر دائمًا سعرًا قابلًا للإلغاء المجّاني متى أمكن، ثم أعد الحجز إن انخفض السعر لاحقًا.','الإقامات في منتصف الأسبوع والموسم الانتقالي أرخص دائمًا تقريبًا من نهايات الأسبوع والموسم المرتفع.']},
   cta:{href:'/hotels', label:{en:'Compare hotel prices →', fr:'Comparer les prix des hôtels →', ar:'قارن أسعار الفنادق →'}, sub:{en:'Hundreds of sites, best deal first.', fr:'Des centaines de sites, la meilleure offre d’abord.', ar:'مئات المواقع، أفضل عرض أولًا.'}}},

  {slug:'how-to-get-through-airport-security-faster', cat:'guide', img:'', date:'2026-07-01',
   title:{en:'How to Get Through Airport Security Faster', fr:'Comment passer la sécurité de l’aéroport plus vite', ar:'كيف تجتاز أمن المطار أسرع'},
   desc:{en:'Simple tips to breeze through airport security — what to wear, how to pack, and what to have ready.', fr:'Des astuces simples pour passer la sécurité sans stress — quoi porter, comment préparer, quoi avoir prêt.', ar:'نصائح بسيطة لاجتياز أمن المطار بسلاسة — ماذا ترتدي، وكيف تحزم، وما الذي تجهّزه.'},
   lead:{en:'Security lines are where trips slow down. A little preparation gets you through quickly and keeps the stress low.', fr:'Les files de sécurité ralentissent les voyages. Un peu de préparation vous fait passer vite et garde le stress au minimum.', ar:'طوابير الأمن هي ما يبطّئ الرحلات. وقليل من التحضير يجعلك تعبر بسرعة ويُبقي التوتّر منخفضًا.'},
   tipsH:{en:'Speed through security', fr:'Passer vite la sécurité', ar:'اعبر الأمن بسرعة'},
   tips:{en:['Wear slip-on shoes and a belt-free outfit so you’re not fumbling at the tray.','Keep liquids (100 ml or less) in one clear bag at the top of your carry-on for quick access.','Take laptops and large electronics out and place them in a separate tray.','Empty your pockets into your bag before you reach the scanner, not at it.','Have your boarding pass and ID ready in hand, and check the rules for your departure airport in advance.'],
         fr:['Portez des chaussures faciles à enfiler et une tenue sans ceinture pour ne pas perdre de temps au bac.','Gardez les liquides (100 ml maximum) dans un sac transparent en haut de votre bagage cabine, accessible rapidement.','Sortez les ordinateurs et gros appareils et placez-les dans un bac séparé.','Videz vos poches dans votre sac avant d’arriver au scanner, pas devant.','Ayez votre carte d’embarquement et votre pièce d’identité en main, et vérifiez à l’avance les règles de votre aéroport de départ.'],
         ar:['ارتدِ حذاءً سهل اللبس وملابس بلا حزام كي لا تتعثّر عند الصينية.','ضع السوائل (100 مل أو أقل) في كيس شفّاف أعلى حقيبة يدك للوصول السريع.','أخرج الحواسيب والأجهزة الكبيرة وضعها في صينية منفصلة.','أفرغ جيوبك في حقيبتك قبل وصولك للماسح، لا عنده.','جهّز بطاقة الصعود والهوية في يدك، وتحقّق مسبقًا من قواعد مطار مغادرتك.']},
   cta:{href:'/flights/', label:{en:'Find your next flight →', fr:'Trouvez votre prochain vol →', ar:'ابحث عن رحلتك القادمة →'}, sub:{en:'Compare hundreds of airlines.', fr:'Comparez des centaines de compagnies.', ar:'قارن مئات الشركات.'}}},

  {slug:'travel-money-tips-avoid-fees-abroad', cat:'guide', img:'', date:'2026-07-01',
   title:{en:'Travel Money Tips: Avoid Fees Abroad', fr:'Argent en voyage : éviter les frais à l’étranger', ar:'نصائح مال السفر: تجنّب الرسوم في الخارج'},
   desc:{en:'How to spend abroad without losing money to bad exchange rates and hidden card fees.', fr:'Comment dépenser à l’étranger sans perdre d’argent en mauvais taux de change et frais cachés.', ar:'كيف تنفق في الخارج دون خسارة المال بأسعار صرف سيّئة ورسوم خفيّة.'},
   lead:{en:'Exchange rates and card fees quietly eat into your travel budget. A few smart choices keep more money in your pocket.', fr:'Les taux de change et les frais de carte grignotent discrètement votre budget. Quelques bons choix gardent plus d’argent dans votre poche.', ar:'تلتهم أسعار الصرف ورسوم البطاقات ميزانيتك بهدوء. وبضعة خيارات ذكية تُبقي مالًا أكثر في جيبك.'},
   tipsH:{en:'Keep more of your money', fr:'Gardez plus d’argent', ar:'احتفظ بمزيد من مالك'},
   tips:{en:['Always pay in the local currency, not your home currency — “dynamic currency conversion” hides a bad rate.','Use a card with no foreign-transaction fees, and tell your bank you’re travelling so it isn’t blocked.','Withdraw larger amounts less often to cut per-withdrawal ATM fees, and decline the machine’s conversion.','Carry a little local cash for taxis, tips and small shops that don’t take cards.','Avoid airport exchange counters — their rates are usually the worst you’ll find.'],
         fr:['Payez toujours en monnaie locale, pas dans votre devise — la « conversion dynamique » cache un mauvais taux.','Utilisez une carte sans frais à l’étranger, et prévenez votre banque de votre voyage pour qu’elle ne la bloque pas.','Retirez de plus gros montants moins souvent pour réduire les frais par retrait, et refusez la conversion du distributeur.','Gardez un peu d’espèces locales pour les taxis, pourboires et petits commerces sans carte.','Évitez les bureaux de change des aéroports — leurs taux sont souvent les pires.'],
         ar:['ادفع دائمًا بالعملة المحلّية لا بعملتك — «التحويل الديناميكي» يخفي سعرًا سيّئًا.','استخدم بطاقة بلا رسوم معاملات أجنبية، وأخبر بنكك بسفرك كي لا تُحظر.','اسحب مبالغ أكبر بمرّات أقل لتقليل رسوم كل سحب، وارفض تحويل الصرّاف.','احمل قليلًا من النقد المحلّي لسيارات الأجرة والإكراميات والمتاجر الصغيرة التي لا تقبل البطاقات.','تجنّب مكاتب الصرافة في المطارات — أسعارها غالبًا الأسوأ.']},
   cta:{href:'/esim', label:{en:'Stay online abroad →', fr:'Restez connecté à l’étranger →', ar:'ابقَ متّصلًا في الخارج →'}, sub:{en:'Compare travel eSIMs.', fr:'Comparez les eSIM de voyage.', ar:'قارن شرائح eSIM للسفر.'}}},

  {slug:'best-winter-sun-destinations', cat:'guide', img:'bali', date:'2026-07-01',
   title:{en:'Best Winter Sun Destinations', fr:'Les meilleures destinations soleil d’hiver', ar:'أفضل وجهات شمس الشتاء'},
   desc:{en:'Where to escape the cold — warm, sunny destinations that are perfect for a winter getaway.', fr:'Où échapper au froid — des destinations chaudes et ensoleillées, parfaites pour une escapade hivernale.', ar:'أين تهرب من البرد — وجهات دافئة ومشمسة مثالية لعطلة شتوية.'},
   lead:{en:'When winter sets in, a few hours on a plane can take you to summer. Here are some of the best places to chase the sun.', fr:'Quand l’hiver s’installe, quelques heures d’avion peuvent vous emmener en été. Voici quelques-uns des meilleurs endroits pour chercher le soleil.', ar:'حين يحلّ الشتاء، قد تنقلك بضع ساعات على متن طائرة إلى الصيف. وإليك بعض أفضل الأماكن لملاحقة الشمس.'},
   tipsH:{en:'Where to find the sun', fr:'Où trouver le soleil', ar:'أين تجد الشمس'},
   tips:{en:['Dubai and the Gulf: warm winters, beaches and big-city comforts from November to March.','Southeast Asia (Thailand, Bali): dry-season sunshine, low prices and beautiful beaches.','The Canary Islands: spring-like weather all winter, just a short flight from Europe and Morocco.','Egypt’s Red Sea: reliable sun and warm water for diving and relaxing.','Southern Spain and Portugal: mild, sunny days when northern Europe is grey.'],
         fr:['Dubaï et le Golfe : hivers doux, plages et confort de grande ville de novembre à mars.','Asie du Sud-Est (Thaïlande, Bali) : soleil de saison sèche, prix bas et plages magnifiques.','Les îles Canaries : un climat printanier tout l’hiver, à un court vol de l’Europe et du Maroc.','La mer Rouge en Égypte : soleil fiable et eau chaude pour la plongée et la détente.','Sud de l’Espagne et Portugal : journées douces et ensoleillées quand le nord de l’Europe est gris.'],
         ar:['دبي والخليج: شتاء دافئ وشواطئ وراحة المدن الكبرى من نوفمبر إلى مارس.','جنوب شرق آسيا (تايلاند، بالي): شمس الموسم الجافّ وأسعار منخفضة وشواطئ جميلة.','جزر الكناري: طقس ربيعي طوال الشتاء، على بُعد رحلة قصيرة من أوروبا والمغرب.','البحر الأحمر في مصر: شمس موثوقة ومياه دافئة للغوص والاسترخاء.','جنوب إسبانيا والبرتغال: أيام معتدلة ومشمسة حين يكون شمال أوروبا رماديًّا.']},
   cta:{href:'/destinations/', label:{en:'Explore destinations →', fr:'Explorer les destinations →', ar:'استكشف الوجهات →'}, sub:{en:'Best time & live prices for each city.', fr:'Meilleure période et prix en direct par ville.', ar:'أفضل وقت وأسعار مباشرة لكل مدينة.'}}},

  {slug:'first-time-flyer-tips', cat:'guide', img:'amsterdam', date:'2026-07-01',
   title:{en:'First Time Flying? Tips for a Smooth Trip', fr:'Premier vol ? Conseils pour un voyage serein', ar:'تسافر جوًّا لأول مرّة؟ نصائح لرحلة سلسة'},
   desc:{en:'A simple guide for first-time flyers — from booking and check-in to security and boarding.', fr:'Un guide simple pour les premiers vols — de la réservation et l’enregistrement à la sécurité et l’embarquement.', ar:'دليل بسيط لمن يسافر جوًّا لأول مرّة — من الحجز والتسجيل إلى الأمن والصعود.'},
   lead:{en:'Your first flight can feel daunting, but the process is simpler than it looks. Know the steps and you’ll move through the airport with confidence.', fr:'Un premier vol peut intimider, mais le déroulé est plus simple qu’il n’y paraît. Connaissez les étapes et vous traverserez l’aéroport avec assurance.', ar:'قد تبدو رحلتك الأولى مخيفة، لكن العملية أبسط ممّا تبدو. اعرف الخطوات وستتنقّل في المطار بثقة.'},
   tipsH:{en:'Before and at the airport', fr:'Avant et à l’aéroport', ar:'قبل المطار وفيه'},
   tips:{en:['Check in online and save your boarding pass to your phone to skip a queue.','Arrive early — about two hours before a short flight and three for a long-haul.','Bring a valid passport or ID, and check visa rules for your destination well in advance.','Follow the carry-on size and 100 ml liquid rules so nothing is taken at security.','Keep documents, phone and charger in one easy-to-reach bag, and watch the screens for your gate.'],
         fr:['Enregistrez-vous en ligne et gardez votre carte d’embarquement sur votre téléphone pour éviter une file.','Arrivez tôt — environ deux heures avant un vol court et trois pour un long-courrier.','Munissez-vous d’un passeport ou d’une pièce valide, et vérifiez bien à l’avance les règles de visa de votre destination.','Respectez la taille du bagage cabine et la règle des 100 ml pour ne rien perdre à la sécurité.','Gardez documents, téléphone et chargeur dans un sac accessible, et surveillez les écrans pour votre porte.'],
         ar:['سجّل الدخول عبر الإنترنت واحفظ بطاقة الصعود في هاتفك لتتجاوز الطابور.','احضر مبكرًا — نحو ساعتين قبل رحلة قصيرة وثلاث لرحلة طويلة.','اصطحب جواز سفر أو هوية سارية، وتحقّق مبكرًا من قواعد تأشيرة وجهتك.','التزم بمقاس حقيبة اليد وقاعدة 100 مل للسوائل كي لا يُصادر شيء عند الأمن.','احتفظ بالوثائق والهاتف والشاحن في حقيبة سهلة الوصول، وراقب الشاشات لبوّابتك.']},
   cta:{href:'/flights/', label:{en:'Book your first flight →', fr:'Réservez votre premier vol →', ar:'احجز رحلتك الأولى →'}, sub:{en:'Compare airlines, cheapest first.', fr:'Comparez les compagnies, les moins chers d’abord.', ar:'قارن الشركات، الأرخص أولًا.'}}},
];

const L = {
  en:{dir:'ltr',lang:'en',home:'/',dest:'/destinations/',blog:'/blog/',hotels:'/hotels',cars:'/cars',transfers:'/transfers',esim:'/esim',comp:'/compensation',
      nav:{flights:'Flights',hotels:'Hotels',cars:'Cars',transfers:'Transfers',esim:'eSIM',dest:'Destinations',blog:'Blog',comp:'Compensation'},
      hubTitle:'Travel Blog — Tips & Guides for Travellers from Morocco | OasisDeal',
      hubDesc:'Practical travel guides for travellers from Morocco: cheap flights, compensation rights, travel eSIMs, Umrah and more.',
      hubH:'Travel tips & guides', hubIntro:'Practical guides for travellers from Morocco — flights, rights, staying online, and getting more from every trip.',
      cats:{flights:'Flights',rights:'Your rights',esim:'eSIM',umrah:'Umrah',guide:'Guide'},
      readMore:'Read', back:'← All articles', published:'Published', by:'By the OasisDeal team',
      relatedH:'Keep exploring', secure:'Secure & free to use · No booking fees',
      mt:function(t){return t+' | OasisDeal';}},
  fr:{dir:'ltr',lang:'fr',home:'/fr/',dest:'/fr/destinations/',blog:'/fr/blog/',hotels:'/hotels',cars:'/cars',transfers:'/transfers',esim:'/esim',comp:'/compensation',
      nav:{flights:'Vols',hotels:'Hôtels',cars:'Voitures',transfers:'Transferts',esim:'eSIM',dest:'Destinations',blog:'Blog',comp:'Indemnisation'},
      hubTitle:'Blog voyage — Conseils & guides pour les voyageurs du Maroc | OasisDeal',
      hubDesc:'Guides pratiques pour les voyageurs du Maroc : vols pas chers, droits à indemnisation, eSIM voyage, Omra et plus.',
      hubH:'Conseils & guides voyage', hubIntro:'Guides pratiques pour les voyageurs du Maroc — vols, droits, rester connecté et profiter de chaque voyage.',
      cats:{flights:'Vols',rights:'Vos droits',esim:'eSIM',umrah:'Omra',guide:'Guide'},
      readMore:'Lire', back:'← Tous les articles', published:'Publié le', by:'Par l’équipe OasisDeal',
      relatedH:'Continuez à explorer', secure:'Sécurisé et gratuit · Sans frais',
      mt:function(t){return t+' | OasisDeal';}},
  ar:{dir:'rtl',lang:'ar',home:'/ar/',dest:'/ar/destinations/',blog:'/ar/blog/',hotels:'/hotels',cars:'/cars',transfers:'/transfers',esim:'/esim',comp:'/compensation',
      nav:{flights:'رحلات',hotels:'فنادق',cars:'سيارات',transfers:'النقل',esim:'eSIM',dest:'الوجهات',blog:'المدوّنة',comp:'تعويضات'},
      hubTitle:'مدوّنة السفر — نصائح وأدلة للمسافرين من المغرب | OasisDeal',
      hubDesc:'أدلة سفر عملية للمسافرين من المغرب: رحلات رخيصة، حقوق التعويض، شرائح eSIM للسفر، العمرة والمزيد.',
      hubH:'نصائح وأدلة السفر', hubIntro:'أدلة عملية للمسافرين من المغرب — الرحلات، الحقوق، البقاء متصلًا، والاستفادة أكثر من كل رحلة.',
      cats:{flights:'رحلات',rights:'حقوقك',esim:'eSIM',umrah:'العمرة',guide:'دليل'},
      readMore:'اقرأ', back:'→ كل المقالات', published:'نُشر في', by:'فريق OasisDeal',
      relatedH:'واصل الاستكشاف', secure:'آمن ومجاني · دون رسوم حجز',
      mt:function(t){return t+' | OasisDeal';}},
};

function pre(lang){ return lang==='en'?'':'/'+lang; }
function homeName(lang){ return lang==='fr'?'Accueil':lang==='ar'?'الرئيسية':'Home'; }
function breadcrumb(items){ return {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':items.map(function(it,i){var o={'@type':'ListItem','position':i+1,'name':it.n}; if(it.u) o.item=it.u; return o;})}; }
const LOGO = '<svg class="logo-mark" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="16" cy="16" r="15" fill="#E8A33D"/><path d="M16 22c0-7 3-10 8-11-1 6-3 9-8 11z" fill="#241F5E"/><path d="M16 22c0-7-3-10-8-11 1 6 3 9 8 11z" fill="#4B3FCB"/><rect x="14.6" y="20" width="2.8" height="5" rx="1" fill="#241F5E"/></svg>';

function featureImg(a, lang){
  if(a.img){
    var exts=['webp','jpg','jpeg','png'];
    for(var i=0;i<exts.length;i++){
      var rel='images/destinations/'+a.img+'.'+exts[i];
      if(fs.existsSync(path.join(ROOT,rel))) return '<img class="dg-photo" src="/'+rel+'" alt="'+a.title[lang]+'" loading="lazy" decoding="async" width="1280" height="540" />';
    }
  }
  return '<svg class="dg-photo dg-svg" viewBox="0 0 1280 460" role="img" aria-label="'+a.title.en+'" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">'
    +'<defs><linearGradient id="g'+a.slug.replace(/[^a-z]/g,'')+'" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#4B3FCB"/><stop offset="1" stop-color="#241F5E"/></linearGradient></defs>'
    +'<rect width="1280" height="460" fill="url(#g'+a.slug.replace(/[^a-z]/g,'')+')"/>'
    +'<circle cx="1080" cy="110" r="60" fill="#E8A33D" opacity="0.9"/>'
    +'<g fill="#F4ECDD" opacity="0.14"><rect x="90" y="300" width="100" height="160"/><rect x="220" y="250" width="80" height="210"/><rect x="330" y="330" width="120" height="130"/><rect x="480" y="240" width="70" height="220"/><rect x="580" y="310" width="130" height="150"/><rect x="740" y="270" width="90" height="190"/><rect x="860" y="330" width="140" height="130"/><rect x="1030" y="290" width="110" height="170"/></g>'
    +'<text x="60" y="240" font-family="Fraunces, Georgia, serif" font-size="46" fill="#FFFBF5" font-weight="600" opacity="0.95">'+L.en.cats[a.cat]+'</text></svg>';
}

var NAVJS='<script>(function(){var C=\'.nav-div{display:inline-block;width:1px;height:18px;background:var(--line);margin:0 6px;vertical-align:middle;}.nav-toggle{display:none;flex-direction:column;justify-content:center;align-items:center;gap:5px;width:42px;height:42px;padding:0;border:1px solid var(--line);border-radius:10px;background:var(--paper);cursor:pointer;}.nav-toggle span{display:block;width:20px;height:2px;background:var(--ink);border-radius:2px;transition:transform .2s,opacity .2s;}.nav-row.menu-open .nav-toggle span:nth-child(1){transform:translateY(7px) rotate(45deg);}.nav-row.menu-open .nav-toggle span:nth-child(2){opacity:0;}.nav-row.menu-open .nav-toggle span:nth-child(3){transform:translateY(-7px) rotate(-45deg);}@media(max-width:1120px){.nav-div{display:none!important;}.nav-row{flex-wrap:nowrap!important;height:60px;position:relative;}.nav-toggle{display:flex;}.nav-links{position:absolute;top:100%;inset-inline-start:0;width:100%;flex-direction:column;align-items:stretch;gap:0!important;background:var(--paper);border:1px solid var(--line);border-radius:0 0 16px 16px;padding:8px;box-shadow:0 14px 30px rgba(24,26,46,.14);display:none!important;z-index:60;}.nav-row.menu-open .nav-links{display:flex!important;}.nav-links .nav-link{display:block!important;padding:13px 12px;font-size:1rem;border-bottom:1px solid var(--line);}.nav-links .btn{margin:10px 4px 4px;justify-content:center;}.nav-links .rp-langs{display:flex;justify-content:center;gap:16px;padding:12px;}.nav-links .rp-langs a{color:var(--ink);opacity:.75;}.nav-links .rp-langs a.on{opacity:1;}}\';function I(){var r=document.querySelector(".nav-row");if(!r||r.querySelector(".nav-toggle"))return;var l=r.querySelector(".nav-links");if(!l)return;var s=document.createElement("style");s.textContent=C;document.head.appendChild(s);var b=document.createElement("button");b.className="nav-toggle";b.type="button";b.setAttribute("aria-label","Menu");b.innerHTML="<span></span><span></span><span></span>";b.addEventListener("click",function(){r.classList.toggle("menu-open");});r.appendChild(b);l.addEventListener("click",function(e){if(e.target.closest("a"))r.classList.remove("menu-open");});}if(document.readyState!=="loading")I();else document.addEventListener("DOMContentLoaded",I);})();</script>';

function nav(lang, langsHtml){ var x=L[lang];
  return '<nav class="nav"><div class="container nav-row"><a class="logo" href="'+x.home+'">'+LOGO+'<span class="logo-word">Oasis<span class="pipe">|</span>Deal</span></a><div class="nav-links">'
    +'<a class="nav-link" href="'+x.home+'">'+x.nav.flights+'</a><a class="nav-link" href="'+x.hotels+'">'+x.nav.hotels+'</a><a class="nav-link" href="'+x.cars+'">'+x.nav.cars+'</a><a class="nav-link" href="'+x.transfers+'">'+x.nav.transfers+'</a><a class="nav-link" href="'+x.esim+'">'+x.nav.esim+'</a><a class="nav-link" href="'+x.comp+'">'+x.nav.comp+'</a><span class="nav-div"></span><a class="nav-link" href="'+x.dest+'">'+x.nav.dest+'</a><a class="nav-link active" href="'+x.blog+'">'+x.nav.blog+'</a>'
    +(langsHtml?'<span class="rp-langs">'+langsHtml+'</span>':'')+'</div></div></nav>'; }
function footer(lang){ var x=L[lang]; return '<footer class="footer"><div class="container"><div class="footer-trust">🔒 '+x.secure+' · Travelpayouts · Stay22 · AirHelp</div><div class="footer-bottom"><span>© <span id="y"></span> OasisDeal</span></div></div></footer><script>document.getElementById("y").textContent=new Date().getFullYear();</script>'+NAVJS; }

var EXTRA = '<style>'
  +'.rp-hero{background:linear-gradient(160deg,var(--majorelle) 0%,var(--majorelle-deep) 100%);color:#fff;padding:48px 0 44px}.rp-hero h1{color:#fff;font-size:clamp(1.8rem,4.4vw,2.9rem);line-height:1.12}.rp-hero .eyebrow{color:rgba(255,255,255,.85)}'
  +'.blog-meta{font-family:"IBM Plex Mono",monospace;font-size:.7rem;letter-spacing:.08em;text-transform:uppercase;color:rgba(255,255,255,.8);margin-top:12px}'
  +'.dg-col{max-width:760px;margin:0 auto}'
  +'.dg-figure{margin:-26px 0 0}.dg-photo{display:block;width:100%;height:auto;max-height:420px;object-fit:cover;border-radius:18px;border:1px solid var(--line);box-shadow:0 20px 44px rgba(24,26,46,.12)}.dg-svg{aspect-ratio:1280/460}'
  +'.dg-article{font-size:1.04rem}.dg-article h2{font-size:1.4rem;margin:32px 0 10px}.dg-lead{font-size:1.15rem;line-height:1.7;color:var(--ink);margin-top:26px;font-weight:500}.dg-article p{line-height:1.75;color:var(--ink-soft);margin-bottom:6px}'
  +'.dg-todo{list-style:none;padding:0;margin:8px 0;display:grid;gap:10px;counter-reset:t}.dg-todo li{position:relative;padding:13px 16px 13px 48px;background:var(--paper);border:1px solid var(--line);border-radius:12px;color:var(--ink)}.dg-todo li::before{counter-increment:t;content:counter(t);position:absolute;inset-inline-start:14px;top:11px;width:22px;height:22px;border-radius:50%;background:var(--majorelle);color:#fff;font-size:.78rem;font-weight:700;display:flex;align-items:center;justify-content:center}'
  +'[dir=rtl] .dg-todo li{padding:13px 48px 13px 16px}'
  +'.blog-cta{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:22px;margin:30px 0;display:flex;flex-wrap:wrap;align-items:center;gap:14px;justify-content:space-between}.blog-cta p{margin:0;color:var(--ink-soft)}.blog-cta strong{color:var(--ink);font-size:1.05rem}'
  +'.nav .rp-langs a{margin-inline-start:8px;color:var(--ink-soft);text-decoration:none;font-size:.85rem}.nav .rp-langs a.on{color:var(--ink);font-weight:700;text-decoration:underline}'
  +'.blog-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px;margin-top:20px}'
  +'.blog-card{display:block;background:var(--paper);border:1px solid var(--line);border-radius:16px;overflow:hidden;text-decoration:none;color:inherit;transition:border-color .15s,transform .15s}.blog-card:hover{border-color:var(--majorelle);transform:translateY(-2px)}'
  +'.blog-card .bc-img{width:100%;height:160px;object-fit:cover;display:block}.blog-card .bc-body{padding:16px}.blog-card .bc-cat{font-family:"IBM Plex Mono",monospace;font-size:.6rem;letter-spacing:.08em;text-transform:uppercase;color:var(--clay-deep);font-weight:600}.blog-card h2{font-size:1.12rem;margin:8px 0 6px;line-height:1.3}.blog-card p{color:var(--ink-soft);font-size:.9rem;line-height:1.5;margin:0}'
  +'</style>';

function head(lang, title, desc, canon, alts, ld){
  return '<!DOCTYPE html>\n<html lang="'+L[lang].lang+'" dir="'+L[lang].dir+'">\n<head>\n<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="p:domain_verify" content="1f6676c70992e08fca792b0978b916b9" />\n'
    +'<title>'+title+'</title>\n<meta name="description" content="'+desc+'" />\n<link rel="canonical" href="'+canon+'" />\n'+alts+'\n'
    +'<meta property="og:title" content="'+title+'" /><meta property="og:description" content="'+desc+'" /><meta property="og:url" content="'+canon+'" /><meta property="og:type" content="article" />\n'
    +'<link rel="icon" type="image/svg+xml" href="/favicon.svg" />\n<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
    +'<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300..900&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">\n<link rel="stylesheet" href="/assets/site.css" />\n'+EXTRA
    +(ld?'\n<script type="application/ld+json">'+JSON.stringify(ld)+'</script>':'')+'\n</head>\n<body>\n';
}
function altsFor(p){ return ['en','fr','ar'].map(function(lg){return '<link rel="alternate" hreflang="'+lg+'" href="https://oasisdeal.com'+(lg==='en'?'':'/'+lg)+p+'" />';}).join('\n')+'\n<link rel="alternate" hreflang="x-default" href="https://oasisdeal.com'+p+'" />'; }
function langSwitch(lang, p){ return ['en','fr','ar'].map(function(lg){return '<a class="'+(lg===lang?'on':'')+'" href="'+(lg==='en'?'':'/'+lg)+p+'">'+lg.toUpperCase()+'</a>';}).join(''); }

function bodyHtml(a, lang){
  var html='<p class="dg-lead">'+a.lead[lang]+'</p>';
  if(a.secs) a.secs.forEach(function(s){ html+='<h2>'+s.h[lang]+'</h2><p>'+s.p[lang]+'</p>'; });
  if(a.tips){ html+='<h2>'+a.tipsH[lang]+'</h2><ol class="dg-todo">'+a.tips[lang].map(function(t){return '<li>'+t+'</li>';}).join('')+'</ol>'; }
  var c=a.cta, href=(c.href.charAt(0)==='/'&&!/^\/(hotels|esim|compensation)(\/|$)/.test(c.href)? pre(lang):'')+c.href;
  html+='<div class="blog-cta"><div><strong>'+c.sub[lang]+'</strong></div><a class="btn btn-primary" href="'+href+'">'+c.label[lang]+'</a></div>';
  return html;
}

function articlePage(a, lang){
  var x=L[lang], p='/blog/'+a.slug, url='https://oasisdeal.com'+pre(lang)+p;
  var ld={'@context':'https://schema.org','@type':'BlogPosting','headline':a.title[lang],'description':a.desc[lang],'datePublished':a.date,'dateModified':a.date,'inLanguage':lang,'author':{'@type':'Organization','name':'OasisDeal'},'publisher':{'@type':'Organization','name':'OasisDeal','logo':{'@type':'ImageObject','url':'https://oasisdeal.com/favicon.svg'}},'mainEntityOfPage':url};
  // related: up to 3 other articles
  var rel=ART.filter(function(o){return o.slug!==a.slug;}).sort(function(x,z){return (x.img?0:1)-(z.img?0:1);}).slice(0,3);
  var related='<div class="blog-grid">'+rel.map(function(o){return blogCard(o,lang);}).join('')+'</div>';
  var crumb=breadcrumb([{n:homeName(lang),u:'https://oasisdeal.com'+x.home},{n:x.nav.blog,u:'https://oasisdeal.com'+x.blog},{n:a.title[lang],u:url}]);
  return head(lang, x.mt(a.title[lang]), a.desc[lang], url, altsFor(p), [ld, crumb])
    + nav(lang, langSwitch(lang,p))
    + '<header class="rp-hero"><div class="container"><div class="dg-col">'
    + '<div class="eyebrow">'+x.cats[a.cat]+'</div>'
    + '<h1>'+a.title[lang]+'</h1>'
    + '<div class="blog-meta">'+x.published+' '+a.date+' · '+x.by+'</div>'
    + '</div></div></header>'
    + '<main class="container" style="padding-top:0;padding-bottom:40px"><div class="dg-col">'
    + '<figure class="dg-figure">'+featureImg(a,lang)+'</figure>'
    + '<article class="dg-article">'+bodyHtml(a,lang)
    + '<p style="margin-top:18px"><a href="'+x.blog+'" style="color:var(--majorelle);font-weight:600;text-decoration:none">'+x.back+'</a></p>'
    + '<h2>'+x.relatedH+'</h2>'+related
    + '</article></div></main>'
    + footer(lang)+STAY22+'\n</body>\n</html>\n';
}

function blogCard(a, lang){
  var x=L[lang], href=pre(lang)+'/blog/'+a.slug;
  return '<a class="blog-card" href="'+href+'">'+featureImgCard(a,lang)
    +'<div class="bc-body"><div class="bc-cat">'+x.cats[a.cat]+'</div><h2>'+a.title[lang]+'</h2><p>'+a.desc[lang]+'</p></div></a>';
}
function featureImgCard(a, lang){
  if(a.img){ var exts=['webp','jpg','jpeg','png']; for(var i=0;i<exts.length;i++){ var rel='images/destinations/'+a.img+'.'+exts[i]; if(fs.existsSync(path.join(ROOT,rel))) return '<img class="bc-img" src="/'+rel+'" alt="'+a.title[lang]+'" loading="lazy" width="280" height="160" />'; } }
  return '<div class="bc-img" style="background:linear-gradient(160deg,var(--majorelle),var(--majorelle-deep));display:flex;align-items:center;justify-content:center"><span style="color:#fff;font-family:\'Fraunces\',serif;font-size:1.3rem;opacity:.9">'+L.en.cats[a.cat]+'</span></div>';
}

function hubPage(lang){
  var x=L[lang], p='/blog/';
  var cards=ART.slice().sort(function(a,b){return (a.img?0:1)-(b.img?0:1);}).map(function(a){return blogCard(a,lang);}).join('');
  var crumb=breadcrumb([{n:homeName(lang),u:'https://oasisdeal.com'+x.home},{n:x.nav.blog,u:'https://oasisdeal.com'+x.blog}]);
  return head(lang, x.hubTitle, x.hubDesc, 'https://oasisdeal.com'+pre(lang)+p, altsFor(p), crumb)
    + nav(lang, langSwitch(lang,p))
    + '<header class="rp-hero"><div class="container"><h1>'+x.hubH+'</h1><p style="opacity:.92;max-width:640px;margin-top:10px;font-size:1.05rem">'+x.hubIntro+'</p></div></header>'
    + '<main class="container" style="padding-top:24px;padding-bottom:44px"><div class="blog-grid">'+cards+'</div></main>'
    + footer(lang)+STAY22+'\n</body>\n</html>\n';
}

function ensure(p){fs.mkdirSync(p,{recursive:true});}
function write(rel,html){var ff=path.join(ROOT,rel);ensure(path.dirname(ff));fs.writeFileSync(ff,html);}

var count=0;
['en','fr','ar'].forEach(function(lang){
  var base=lang==='en'?'blog':path.join(lang,'blog');
  ART.forEach(function(a){ write(path.join(base,a.slug+'.html'), articlePage(a,lang)); count++; });
  write(path.join(base,'index.html'), hubPage(lang));
});
console.log('wrote', count, 'blog articles +', 3, 'hubs');

// merge blog URLs into sitemap.xml (idempotent) + write .blog-urls.json
var blogUrls=[];
['','/fr','/ar'].forEach(function(pre){
  blogUrls.push('https://oasisdeal.com'+pre+'/blog/');
  ART.forEach(function(a){ blogUrls.push('https://oasisdeal.com'+pre+'/blog/'+a.slug); });
});
var smPath=path.join(ROOT,'sitemap.xml');
if(fs.existsSync(smPath)){
  var sm=fs.readFileSync(smPath,'utf8');
  blogUrls.forEach(function(u){ if(sm.indexOf('<loc>'+u+'</loc>')===-1){ sm=sm.replace('</urlset>','  <url><loc>'+u+'</loc></url>\n</urlset>'); } });
  fs.writeFileSync(smPath,sm);
  console.log('merged', blogUrls.length, 'blog urls into sitemap.xml');
}
fs.writeFileSync(path.join(ROOT,'.blog-urls.json'), JSON.stringify(blogUrls));

/* ---- full multi-column footer (shared, appended to each generator) ---- */
function fullFooter(lang){
  var P=lang==='en'?'':'/'+lang, H=lang==='en'?'/':'/'+lang+'/';
  var T={en:{ex:'Explore',co:'Company',pr:'Top destinations',gu:'Guides',tag:'Find your savings oasis — flights, hotels and compensation, compared honestly.',flights:'Flights',hotels:'Hotels',cars:'Cars',transfers:'Transfers',esim:'eSIM',comp:'Compensation',dest:'Destinations',blog:'Blog',about:'About',contact:'Contact',privacy:'Privacy',rights:'Flight delay rights',umrah:'How to avoid jet lag',vs:'Best winter sun spots',allr:'All destinations →',secure:'Secure & free to use · No booking fees',r:[['dubai','Dubai'],['tokyo','Tokyo'],['paris','Paris']]},
    fr:{ex:'Explorer',co:'Société',pr:'Meilleures destinations',gu:'Guides',tag:'Trouvez votre oasis d’économies — vols, hôtels et indemnisation, comparés honnêtement.',flights:'Vols',hotels:'Hôtels',cars:'Voitures',transfers:'Transferts',esim:'eSIM',comp:'Indemnisation',dest:'Destinations',blog:'Blog',about:'À propos',contact:'Contact',privacy:'Confidentialité',rights:'Indemnisation de vol',umrah:'Éviter le décalage horaire',vs:'Destinations soleil d’hiver',allr:'Toutes les destinations →',secure:'Sécurisé et gratuit · Sans frais',r:[['dubai','Dubaï'],['tokyo','Tokyo'],['paris','Paris']]},
    ar:{ex:'استكشف',co:'الشركة',pr:'أفضل الوجهات',gu:'أدلة',tag:'اعثر على واحة التوفير — رحلات وفنادق وتعويضات، نقارنها بصدق.',flights:'رحلات',hotels:'فنادق',cars:'سيارات',transfers:'النقل',esim:'eSIM',comp:'تعويضات',dest:'الوجهات',blog:'المدوّنة',about:'من نحن',contact:'اتصل بنا',privacy:'الخصوصية',rights:'تعويض تأخّر الرحلة',umrah:'كيف تتجنّب اضطراب الرحلات',vs:'وجهات شمس الشتاء',allr:'كل الوجهات →',secure:'آمن ومجاني · دون رسوم حجز',r:[['dubai','دبي'],['tokyo','طوكيو'],['paris','باريس']]}}[lang];
  function col(h,links){return '<div class="footer-col"><h4>'+h+'</h4>'+links.map(function(l){return '<a href="'+l[0]+'">'+l[1]+'</a>';}).join('')+'</div>';}
  var explore=col(T.ex,[[H,T.flights],['/hotels',T.hotels],['/transfers',T.transfers],['/esim',T.esim],['/compensation',T.comp],[P+'/destinations/',T.dest],[P+'/blog/',T.blog]]);
  var company=col(T.co,[['/about',T.about],['/contact',T.contact],['/privacy',T.privacy]]);
  var routes=col(T.pr,T.r.map(function(z){return [P+'/destinations/'+z[0],z[1]];}).concat([[P+'/destinations/',T.allr]]));
  var guides=col(T.gu,[[P+'/flight-rights',T.rights],[P+'/blog/how-to-avoid-jet-lag',T.umrah],[P+'/blog/best-winter-sun-destinations',T.vs]]);
  return '<footer class="footer"><div class="container">'
    +'<div class="footer-top"><div class="footer-brand"><a class="logo footer-logo" href="'+H+'">'+LOGO+'<span class="logo-word">Oasis<span class="pipe">|</span>Deal</span></a><p class="footer-tag">'+T.tag+'</p>'+'<div class="footer-social"><a class="footer-ig" href="https://www.instagram.com/oasisdealtravel/" target="_blank" rel="noopener" aria-label="Instagram"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor" stroke="none"/></svg><span>Follow us on Instagram</span></a><script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js" async></script><div class="trustpilot-widget" data-locale="en-US" data-template-id="56278e9abfbbba0bdcd568bc" data-businessunit-id="6a425cb3f6d6bcdc734d3d22" data-style-height="52px" data-style-width="100%" data-token="da476c82-b569-4dfe-bb19-b4af4c691150"><a href="https://www.trustpilot.com/review/oasisdeal.com" target="_blank" rel="noopener">Trustpilot</a></div></div>'+'</div>'
    +'<div class="footer-cols">'+explore+routes+guides+company+'</div></div>'
    +'<div class="footer-trust">🔒 '+T.secure+' · Travelpayouts · Stay22 · AirHelp</div>'
    +'<div class="footer-bottom"><span>© <span id="y"></span> OasisDeal</span></div>'
    +'</div></footer><script>document.getElementById("y").textContent=new Date().getFullYear();</script>'+NAVJS;
}
function footer(lang){return fullFooter(lang);}

